<?php
	if(isset($this->a_bilder) &&
	   is_array($this->a_bilder))
	{
		foreach($this->a_bilder as $a_bild)
		{
?>
		<div class="miniaturbild">
			<div class="miniaturbild-delete" ></div>
			<img class="miniaturbild-src" class="" 
				 src="<?php echo '/butler/create-thumb/file/' . base64_encode($a_bild[CAD_File::SYS_PFAD]) . '/height/50/width/67/prio_height/true';?>" 
				 data-src="<?php echo base64_encode($a_bild[CAD_FILE::HTML_PFAD]);?>" 
				 data-file="<?php echo base64_encode($a_bild[CAD_FILE::FILE]);?>" />
		</div>
<?php 
		}
	}
?>
		<div class="miniaturbild">
			<img class="miniaturbild-add" src="/images/content/statisch/grafiken/add_normal.png" />
		</div>