<?php
    if(is_array($this->a_uebungen))
    {
        foreach($this->a_uebungen as $a_uebung)
        {
            $this->assign($a_uebung);
            echo $this->render('uebungen/uebung-loop.phtml');
        }
    }
?>
<script type="text/javascript">
    jQuery('document').ready(function()
    {
        jQuery('.uebung-delete').unbind('click');
        jQuery('.uebung-delete').bind('click', function()
        {
            if(confirm('Diese Übung wirklich löschen?\n'))
            {
                jQuery(this).loescheUebung();
            }
        });
        
        jQuery.fn.loescheUebung = function()
        {
            var i_uebung_id = jQuery(this).data('uebung-id');
            var that = this;
            
            if(isNumber(i_uebung_id) &&
               0 < i_uebung_id)
            {
                var url = "/uebungen/loesche-uebung/";
                var obj_params = {'id': i_uebung_id, 'ajax': true};
                
                jQuery.post(url, obj_params, function(response)
                {
                    try
                    {
                        response = JSON.parse(response);
                        var cad_obj_messages = new CAD.Message();
                        cad_obj_messages.init(response);
                        
                        if(cad_obj_messages.open())
                        {
                            jQuery(that).parent().fadeOut();
                        }
                    }
                    catch(e)
                    {
                        alert(response);
                    }
                });
            }
            else
            {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init([{'type': 'fehler', 'message': 'Fehler bei der Übergabe!<br /><br />Ich kann diese Übung leider nicht löschen!'}]);
                obj_cad_messages.open();
            }
        };
    });
</script>