<?php
$beanspruchung_pos_x = -100;

if($this->uebung_muskel_beanspruchung > 0)
{
    $beanspruchung_pos_x = -100 + ($this->uebung_muskel_beanspruchung * 20);
}
?>
    <span class="muskel-name"
          data-muskel-name="<?php echo $this->muskel_name;?>"
          data-muskel-id="<?php echo $this->muskel_id;?>"
        style="clear: both; float: left; display: inline; font-size: 10px; margin-left: 15px; margin-top: 4px; width: 100px;">
        <?php echo $this->muskel_name;?>
    </span>
    <div class="muskel"
         data-muskel-name="<?php echo $this->muskel_name;?>"
         data-muskel-id="<?php echo $this->muskel_id;?>"
         style="float: left; margin-left: 15px; display: inline; border-radius: 5px; border: 1px solid lightgray;">
        <img src="/images/content/statisch/grafiken/beanspruchung.png"
             class="muskel-beanspruchung"
             style="background-image: url('/images/content/statisch/grafiken/beanspruchung_bg_neu.png');
                    background-repeat: no-repeat;
                    background-position: <?php echo $beanspruchung_pos_x;?>px <?php echo $beanspruchung_pos_x;?>px;
                    width: 100px; height: 20px;
                    background-color: #EEEEEE;"
            data-muskel-beanspruchung="<?php echo $this->uebung_muskel_beanspruchung;?>"
            data-background_position="<?php echo $beanspruchung_pos_x;?>px <?php echo $beanspruchung_pos_x;?>px">
    </div>
