<?php
    $beanspruchung_pos_x = -100;
    
    if($this->uebung_muskelgruppe_beanspruchung > 0)
    {
        $beanspruchung_pos_x = -100 + ($this->uebung_muskelgruppe_beanspruchung * 20);
    }
?>

<div class="muskelgruppe" style="margin-top: 5px; position: relative; width: 325px;">
    <input type="text" class="muskelgruppe_name"
           style="float: left;"
           value="<?php echo $this->muskelgruppe_name;?>" 
           data-muskelgruppe-name="<?php echo $this->muskelgruppe_name;?>" 
           data-muskelgruppe-id="<?php echo $this->muskelgruppe_id;?>" />
    <div style="float: left; margin-left: 10px;">
    <img src="/images/content/statisch/grafiken/beanspruchung.png" class="muskelgruppe_beanspruchung" 
         <?php if($this->uebung_muskelgruppe_beanspruchung > 0){ echo ' data-background_position="' . $beanspruchung_pos_x . 'px ' . $beanspruchung_pos_x . 'px"';}?>
         <?php if($this->uebung_muskelgruppe_beanspruchung > 0){ echo ' data-muskelgruppe-beanspruchung="' . $this->uebung_muskelgruppe_beanspruchung . '"';}?>
         style="background-image: url('/images/content/statisch/grafiken/beanspruchung_bg_neu.png');
            background-repeat: no-repeat;
            background-position: <?php echo $beanspruchung_pos_x;?>px <?php echo $beanspruchung_pos_x;?>px;
            width: 100px; height: 20px;
            background-color: #EEEEEE;">
    </div>
        <img src="/images/content/statisch/grafiken/delete.png" 
             title="zum entfernen hier klicken!" 
             style="position: absolute; height: 20px; width: 20px;
                    right: 5px; top: 0; <?php if($this->uebung_muskelgruppe_id > 0){ echo ' display: block; ';} else
                    { echo ' display: none; ';}?>"
             class="muskelgruppe-delete" />
    <br class="clearfix" />
</div>