<?php
    $vorschaubild = '/images/content/statisch/grafiken/blank.gif';
    if(strlen(trim($this->uebung_vorschaubild)) > 0)
    {
        $vorschaubild_pfad = '/images/content/dynamisch/uebungen/' . $this->uebung_id . '/' . $this->uebung_vorschaubild;
        if(file_exists(getcwd() . $vorschaubild_pfad) &&
           is_file(getcwd() . $vorschaubild_pfad) &&
           is_readable(getcwd() . $vorschaubild_pfad))
        {
            $vorschaubild = $vorschaubild_pfad;
        }
    }
echo '/butler/create-thumb/file/' . base64_encode(getcwd() . $vorschaubild) . '/width/200/';
?>
<div style="position: relative;">
    <img src="<?php echo '/butler/create-thumb/file/' . base64_encode(getcwd() . $vorschaubild) . '/width/200/';?>" style="width: 200px; float: left; display: inline;" />
    <div style="float: left; display: inline;">
        <a href="/uebungen/edit/id/<?php echo $this->uebung_id;?>"
           style="text-decoration: none;">
            <?php echo $this->uebung_name;?>
        </a>
    </div>
    <img src="/images/content/statisch/grafiken/delete.png"
         class="uebung-delete"
         data-uebung-id="<?php echo $this->uebung_id;?>"
         style="position: absolute; top: 0; right: 0;" />
    <br class="clearfix" />
</div>
