<a name="right" />
<?php echo $this->optionContent;?>

<input type="hidden" name="id" id="id" class="id" value="<?php echo $this->id;?>" />

<button class="save btn btn-primary btn-block">
    <?php echo $this->translate('label_save');?>
</button>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.save').unbind('click').click(function() {
            var hasError = false;
            var messages = '<ul>';
            var name = jQuery('.option-name').val();

            if (!name.length) {
                hasError = true;
                messages += '<li><?php echo $this->translate('tooltip_needs_name');?></li>';
            }

            if (!hasError) {
                var url = "/"+controller+"/save";
                jQuery.post(url, {
                    name: name,
                    value: jQuery('.option-value').val(),
                    id: jQuery('.id').val(),
                    ajax: true
                }, function(response) {
                    jQuery.post('/'+controller+'/save', saveData, function(response) {
                        var json = JSON.parse(response);

                        if (200 == json.state) {
                            showDialog(json.message, BootstrapDialog.TYPE_SUCCESS);
                        } else {
                            showDialog(json.message, BootstrapDialog.TYPE_DANGER);
                        }
                    });
                });
            } else {
                messages += '</ul>';
                showDialog(messages, BootstrapDialog.TYPE_DANGER);
            }
        });
    });
</script>