<?php
    if(is_array($this->a_geraetegruppen))
    {
        foreach($this->a_geraetegruppen as $a_geraetegruppe)
        {
            $this->assign($a_geraetegruppe);
            echo $this->render('geraetegruppen/geraetegruppe-loop.phtml');
        }
    }
?>

<script type="text/javascript">
    jQuery('document').ready(function()
    {
        jQuery('.geraetegruppe-delete').unbind('click');
        jQuery('.geraetegruppe-delete').bind('click', function()
        {
            if(confirm('Diese Geraetegruppe wirklich löschen?\n\nAchtung:\n' +
                       'Wenn Sie diese Geraetegruppe löschen, werden auch alle ' +
                       'mit Ihr verknüpften Übungen gelöscht!'))
            {
                jQuery(this).loescheGeraetegruppe();
            }
        });
        
        jQuery.fn.loescheGeraetegruppe = function()
        {
            var i_geraetegruppe_id = jQuery(this).data('geraetegruppe-id');
            var that = this;
            
            if(isNumber(i_geraetegruppe_id) &&
               0 < i_geraetegruppe_id)
            {
                var url = "/geraetegruppen/loesche-geraetegruppe/";
                var obj_params = {'id': i_geraetegruppe_id, 'ajax': true};
                
                jQuery.post(url, obj_params, function(response)
                {
                    try
                    {
                        response = JSON.parse(response);
                        var cad_obj_messages = new CAD.Message();
                        cad_obj_messages.init(response);
                        
                        if(cad_obj_messages.open())
                        {
                            jQuery(that).parent().fadeOut();
                        }
                    }
                    catch(e)
                    {
                        alert(response);
                    }
                });
            }
            else
            {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init([{'type': 'fehler', 'message': 'Fehler bei der Übergabe!<br /><br />Ich kann diese Geraetegruppe leider nicht löschen!'}]);
                obj_cad_messages.open();
            }
        };
    });
</script>
