<div id="<?php echo $this->selectId;?>"
     class="form-group <?php echo $this->optionClassName;?> option-input dropdown"
     data-value="<?php echo $this->currentValue;?>"
     data-value-orig="<?php echo $this->currentValue;?>"
     data-base-value="<?php echo $this->baseValue;?>"
     data-option-id="<?php echo $this->optionId;?>"
    <?php echo $this->additionalDataInformation;?>>
    <label>
        <?php echo $this->optionLabelText;?>
    </label>
    <button class="btn btn-primary dropdown-toggle <?php echo $this->selectClass;?>" type="button" data-toggle="dropdown">
        <?php echo $this->optionSelectText;?>
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" >
        <?php echo $this->optionsContent;?>
    </ul>
    <?php
    if ($this->optionDeleteShow) {
        ?>
        <span class="delete option-delete glyphicon glyphicon-remove-sign"
              data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_delete_option');?>">
        </span>
    <?php
    }
    ?>
    <br class="clear-fix" />
</div>