<div class="widget current-training-plan-container"
     id="<?php echo $this->training_diary_x_training_plan_id;?>"
     data-id="<?php echo $this->dashboardXWidgetId;?>"
     data-training-plan-id="<?php echo $this->training_plan_id;?>">
    <div class="current-training-plan-header">
        <?php echo $this->translate('label_current_training_plan');?>:
        <?php if ($this->training_plan_name) { echo '(' . $this->training_plan_name . ')';}?>
        <div class="current-training-plan-options">
<!--            <span class="glyphicon glyphicon-info-sign"></span>-->
            <a href="/training-diaries/start/id/<?php echo $this->training_plan_id;?>">
                <span class="glyphicon glyphicon-play"></span>
            </a>
        </div>
    </div>
    <?php echo $this->exercisesContent;?>
</div>