<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="/js/c3.js"></script>

<div class="col-sm-12 text-center">
    <p>
        <button type="button" id="demo" class="btn btn-default btn-lg" data-demo="">
            <span class="glyphicon glyphicon-play"></span>
            Start the demo
        </button>
    </p>
</div>


<?php
    echo $this->activeTrainingDiary;
?>

<?php
    echo $this->chartContent;
?>

<script type="text/javascript" src="/js/tainingsmanager_tour.js"></script>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('body').css('overflow', 'auto');
        var demoButton = jQuery('#demo');

        demoButton.unbind('click').click(function() {
            tour.restart();
        });
    });
</script>
