<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="/js/c3.js"></script>

<?php
    echo $this->activeTrainingDiary;
?>

<?php
    echo $this->chartContent;
?>



<script type="text/javascript">
    jQuery(document).ready(function() {
//        jQuery('.current-training-plan-options .glyphicon-play').unbind('click').click(function() {
//
//        });
    });
</script>