<?php
    $obj_cad_filter_ubb_replace = new CAD_Filter_UbbReplace();
    $bild_pfad = '/images/content/dynamisch/geraete/' . $this->geraet_id . '/';
    $bild_temp_pfad = '/tmp/geraete/';
    $obj_cad_filter_ubb_replace->setBilderPfad($bild_pfad);
    $obj_cad_filter_ubb_replace->setTempBilderPfad($bild_temp_pfad);
    $vorschaubild = '/images/content/statisch/grafiken/kein_bild.png';

    if(strlen(trim($this->geraet_vorschaubild)) > 0 &&
        file_exists(getcwd() . $bild_pfad . $this->geraet_vorschaubild) &&
        is_file(getcwd() . $bild_pfad . $this->geraet_vorschaubild) &&
        is_readable(getcwd() . $bild_pfad . $this->geraet_vorschaubild))
    {
        $vorschaubild = $bild_pfad . $this->geraet_vorschaubild;
    }
?>
<div>
    <h3>
        Gerät Name:<span
            class="editable" 
            style="margin-left: 20px; border-bottom: 1px dotted gray;"
            id="geraet_name" data-cad-cms-content-orig="<?php echo base64_encode($this->geraet_name);?>" 
		><?php echo $this->geraet_name;?></span>
    </h3>

    <br class="clearfix" />

    <img src="<?php echo $vorschaubild?>"
         class="editable vorschaubild"
         alt="Vorschaubild"
         style="margin-top: 15px;"
         title="klicken Sie hier, um ein Bild hochzuladen"
         id="geraet_vorschaubild" />

    <br class="clearfix" />
    
    <h3 style="margin-top: 15px; font-size: 12px;">
        Mögliche Einstellungen:
    </h3>

    <br class="clearfix" />
    
    <textarea
        class="" 
        style="margin-left: 20px; margin-top: 5px; border-bottom: 1px dotted gray; font-size: 12px; width: 600px; height: 50px;"
        id="geraet_moegliche_einstellungen" data-cad-cms-content-orig="<?php echo base64_encode($this->geraet_moegliche_einstellungen);?>"
        ><?php echo $this->geraet_moegliche_einstellungen;?></textarea>

    <br class="clearfix" />
    
    <h3 style="margin-top: 15px; font-size: 12px;">
        Mögliche Sitzpositionen:
    </h3>

    <br class="clearfix" />
    
    <textarea
        class="" 
        style="margin-left: 20px; margin-top: 5px; border-bottom: 1px dotted gray; font-size: 12px; width: 600px; height: 50px;"
        id="geraet_moegliche_sitzpositionen" data-cad-cms-content-orig="<?php echo base64_encode($this->geraet_moegliche_sitzpositionen);?>"
        ><?php echo $this->geraet_moegliche_sitzpositionen;?></textarea>

    <br class="clearfix" />
    
    <h3 style="margin-top: 15px; font-size: 12px;">
        Mögliche Gewichte:
    </h3>

    <br class="clearfix" />
    
    <textarea
        class="" 
        style="margin-left: 20px; margin-top: 5px; border-bottom: 1px dotted gray; font-size: 12px; width: 600px; height: 50px;"
        id="geraet_moegliche_gewichte" data-cad-cms-content-orig="<?php echo base64_encode($this->geraet_moegliche_gewichte);?>"
        ><?php echo $this->geraet_moegliche_gewichte;?></textarea>

    <br class="clearfix" />
    
    <input type="hidden" class="id" name="geraet-id" id="geraet_id" value="<?php echo $this->geraet_id;?>" />
</div>

<br class="clearfix" />

<h3 style="margin-top: 15px;">
    Gerätebilder:
</h3>

<div class="vorschau_bilder"
     style="margin-top: 5px;">

</div>

<br class="clearfix" />

<button onclick="save();" 
        class="button"
        style="margin-top: 15px;">
    Speichern
</button>

<script type="text/javascript">
	controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

	function save()
	{
            var b_fehler = false;
            var a_messages = new Array();
            
            if(!trim(jQuery('#geraet_name').html()).length)
            {
                b_fehler = true;
                a_messages.push({'type': 'fehler', 'message': 'Das Geraet braucht einen Namen!'});
            }
            
            if(!b_fehler)
            {
                jQuery().setEditedElements('geraet_id',                         jQuery('#geraet_id').val());
                jQuery().setEditedElements('geraet_moegliche_einstellungen',    Base64.encode(jQuery('#geraet_moegliche_einstellungen').val()));
                jQuery().setEditedElements('geraet_moegliche_sitzpositionen',   Base64.encode(jQuery('#geraet_moegliche_sitzpositionen').val()));
                jQuery().setEditedElements('geraet_moegliche_gewichte',         Base64.encode(jQuery('#geraet_moegliche_gewichte').val()));
                jQuery().setEditedElements('geraet_id',                         jQuery('#geraet_id').val());
                jQuery().setEditedElements('geraet_id',                         jQuery('#geraet_id').val());
                jQuery().setEditedElements('geraet_vorschaubild',               jQuery('#geraet_vorschaubild').data('file'));
                jQuery().setAjax(true);

                CADEditSave();
            }
            else
            {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init(a_messages);
                obj_cad_messages.open();
            }
        }
        edit_init(true);
//        initGeraeteEdit();
</script>
