<div style="position: relative; width: 300px; margin-top: 10px;">
     <a href="/geraete/edit/id/<?php echo $this->geraet_id;?>" 
   style="margin-top: 5px; text-decoration: none;">
    <?php echo $this->geraet_name;?>
    </a>
    <br />
    <img src="/images/content/statisch/grafiken/delete.png" 
         class="geraet-delete"
         data-geraet-id="<?php echo $this->geraet_id;?>"
         style="position: absolute; top: 0; right: 0;" />
</div>
