<div style="position: relative;">
    <img src="/images/content/statisch/grafiken/close_button.png" 
         style="position: absolute; top: -25px; right: -30px;"
         onclick="jQuery(this).parent().parent().fadeOut();" />
<?php
    if(is_array($this->a_geraete_vorschlaege) &&
       count($this->a_geraete_vorschlaege) > 0)
    {
        foreach($this->a_geraete_vorschlaege as $a_geraet_vorschlag)
        {
            $this->assign($a_geraet_vorschlag);
            echo $this->render('geraete/geraet-vorschlag-loop.phtml');
        }
    }
    else
    {
        echo "Leider wurde kein entsprechendes Gerät gefunden!";
    }
?>
</div>
