<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
    if(is_array($this->a_geraet_moegliche_einstellungen) &&
       count($this->a_geraet_moegliche_einstellungen) > 0)
    {
?>
        <select id="geraet_moegliche_einstellungen"
                style="margin-left: 15px;">
            <option value="-1" >Bitte wählen</option>
<?php
        foreach($this->a_geraet_moegliche_einstellungen as $key => $moegliche_einstellung)
        {
?>
            <option value="<?=$key?>"><?=$moegliche_einstellung?></option>
<?php
        }
?>
        </select>
<?php
    }
    else if($this->geraet_moegliche_einstellung)
    {
        echo $this->geraet_moegliche_einstellung . "<br />";
    }
?>
<script type="text/javascript">
    jQuery('#geraet_moegliche_einstellungen').find('option').each(function()
    {
        jQuery(this).unbind('click');
        jQuery(this).bind('click', function()
        {
            if(jQuery(this).val() == -1)
            {
                jQuery('#uebung_geraet_einstellung_name').val('');
            }
            else
            {
                jQuery('#uebung_geraet_einstellung_name').val(jQuery(this).text());
            }
        });
    });
</script>