<div>
    <h3>
        Muskelgruppe Name:<span 
            class="editable" 
            style="margin-left: 20px; border-bottom: 1px dotted gray;"
            id="muskelgruppe_name" data-cad-cms-content-orig="<?php echo base64_encode($this->muskelgruppe_name);?>" 
		><?php echo $this->muskelgruppe_name;?></span>
    </h3>
    
    <br class="clearfix" />
    
    <h3 style="float: left; display: inline; margin-top: 15px;">
        Muskeln:
    </h3>
    
    <img class="muskel-add" src="/images/content/statisch/grafiken/add_normal.png" 
         style="width: 30px; float: left; display: inline; margin-top: 15px;"/>
    
    <br class="clearfix" />
    
    <div class="muskelgruppe-muskeln"
         style="margin-top: 5px;">
        
    </div>
    
    <br class="clearfix" />
    
    <input type="hidden" class="id" name="muskelgruppe-id" id="muskelgruppe_id" value="<?php echo $this->muskelgruppe_id;?>" />
</div>

<br class="clearfix" />

<div class="muskel-vorschlaege" 
     style="position: absolute; left: -5000px; top: -5000px; padding: 10px;
            background-color: #FFFFFF; opacity: 0.9; 
            box-shadow: 5px 5px 5px #111111;" ></div>

<button onclick="save();" 
        style="margin-top: 15px;"
        class="button">
    Speichern
</button>

<script type="text/javascript">
	controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

	function save()
	{
            var b_fehler = false;
            var a_messages = new Array();
            
            if(!trim(jQuery('#muskelgruppe_name').html()).length)
            {
                b_fehler = true;
                a_messages.push({'type': 'fehler', 'message': 'Die Muskelgruppe braucht einen Namen!'});
            }
            
            var elemente_muskeln = jQuery('.muskelgruppe-muskeln').find('.muskel');
            var muskeln = [];

            for(var i = 0, len = elemente_muskeln.length; i < len; i++)
            {
                var muskel_id              = jQuery(elemente_muskeln[i]).find('.muskel-name').data('muskel-id');
                var muskel_beanspruchung   = jQuery(elemente_muskeln[i]).find('.muskel-beanspruchung').data('muskel-beanspruchung');
                
                if(muskel_id)
                {
                    muskeln.push({'id': muskel_id, 'beanspruchung': muskel_beanspruchung});
                }
            }
            
            if(!muskeln.length)
            {
                b_fehler = true;
                a_messages.push({'type': 'fehler', 'message': 'Es muss mindestens ein Muskel für diese Muskelgruppe vollständig ausgefüllt sein!'});
            }
            
            if(!b_fehler)
            {
                jQuery().setEditedElements('muskelgruppe_muskeln',   muskeln);
                jQuery().setEditedElements('muskelgruppe_id',        jQuery('#muskelgruppe_id').val());
                jQuery().setAjax(true);

                CADEditSave();
            }
            else
            {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init(a_messages);
                obj_cad_messages.open();
            }
        }
        edit_init(false);
        initMuskelnEdit();
</script>