<?php
    if(isset($this->json_string))
    {
        echo $this->json_string;
    }
    else if(is_array($this->a_muskelgruppe_muskeln) &&
            count($this->a_muskelgruppe_muskeln) > 0)
    {
        foreach($this->a_muskelgruppe_muskeln as $a_muskelgruppe_muskel)
        {
            $this->assign($a_muskelgruppe_muskel);
            echo $this->render('muskelgruppen/muskel-edit-loop.phtml');
        }
    }
    $this->assign('muskelgruppe_muskel_beanspruchung', '');
    $this->assign('muskel_id', '');
    $this->assign('muskel_name', '');
    echo $this->render('muskelgruppen/muskel-edit-loop.phtml');
?>
<script type="text/javascript">
    initMuskelnEdit();
</script>
