<?php
    $beanspruchung_pos_x = -100;
    
    if($this->uebung_muskelgruppe_beanspruchung > 0)
    {
        $beanspruchung_pos_x = -100 + ($this->uebung_muskelgruppe_beanspruchung * 20);
    }
?>
<div style="clear: both; margin-top: 15px; position: relative; width: 300px;">
    <a href="/muskelgruppen/edit/id/<?php echo $this->muskelgruppe_id;?>" 
       style="text-decoration: none;">
        <?php echo $this->muskelgruppe_name;?>
    </a>
    <br class="clearfix" />
<?php
    if(is_array($this->a_muskelgruppe_muskeln))
    {
        foreach($this->a_muskelgruppe_muskeln as $a_muskelgruppe_muskel)
        {
            $this->assign($a_muskelgruppe_muskel);
            echo $this->render('muskelgruppen/muskelgruppe-muskel-loop.phtml');
        }
    }
?>
    <img src="/images/content/statisch/grafiken/delete.png"
         class="muskelgruppe-delete"
         data-muskelgruppe-id="<?php echo $this->muskelgruppe_id;?>"
         style="position: absolute; top: 0; right: 0;" />
    <br class="clearfix" />
</div>
