<?php
    $beanspruchung_pos_x = -50;
    
    if($this->muskelgruppe_muskel_beanspruchung > 0)
    {
        $beanspruchung_pos_x = -50 + ($this->muskelgruppe_muskel_beanspruchung * 10);
    }
?>
<div class="muskel" 
     style="margin-top: 5px; position: relative; width: 100px; 
            margin-left: 30px; float: left; display: inline;">
    <p style="font-size: 10px;"><?php echo $this->muskel_name;?></p>
    <div >
    <img src="/images/content/statisch/grafiken/beanspruchung.png" 
             style="background-image: url('/images/content/statisch/grafiken/beanspruchung_bg_klein.png');
                    background-repeat: no-repeat;
                    background-position: <?php echo $beanspruchung_pos_x;?>px <?php echo $beanspruchung_pos_x;?>px;
                    width: 50px; height: 10px;
                    background-color: #EEEEEE;">
    </div>
</div>