<a name="right" />
<div>
    <h3>
        <?php echo $this->translate('label_device_group_name');?>:<span
            class="editable" 
            style="margin-left: 20px; border-bottom: 1px dotted gray;"
            id="device_group_name" data-cad-cms-content-orig="<?php echo base64_encode($this->device_group_name);?>"
            data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_device_group_name');?>"
		><?php echo $this->device_group_name;?></span>
    </h3>
    
    <br class="clear-fix" />
    
    <h3 style="float: left; display: inline; margin-top: 15px;">
        <?php echo $this->translate('label_devices');?>:
    </h3>
    
    <span class="add device-add glyphicon glyphicon-plus-sign" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_add_new_device_input');?>">

    </span>
    
    <br class="clear-fix" />
    
    <div class="device-group-devices"
         style="margin-top: 5px;">
        <?php echo $this->deviceGroupDevicesContent;?>
    </div>
    
    <br class="clear-fix" />
    
    <input type="hidden" class="id" name="device-group-id" id="device_group_id" value="<?php echo $this->device_group_id;?>" />
</div>

<br class="clear-fix" />

<div class="proposals"
     style="position: absolute; left: -5000px; top: -5000px; padding: 10px;
            background-color: #FFFFFF; opacity: 0.9; 
            box-shadow: 5px 5px 5px #111111;" ></div>

<button class="save btn btn-primary btn-block">
    <?php echo $this->translate('label_save');?>
</button>

<script type="text/javascript">
	controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

	function save() {
            var hasErrors = false;
            var a_messages = [];
            
            if (!jQuery.trim(jQuery('#device_group_name').html()).length) {
                hasErrors = true;
                a_messages.push({'type': 'fehler', 'message': '<?php echo $this->translate('tooltip_device_group_needs_name');?>'});
            }
            
            var devicesCollection = jQuery('.device-group-devices').find('.device');
            var devices = [];

            for (var i = 0, len = devicesCollection.length; i < len; i++) {
                var device_id              = jQuery(devicesCollection[i]).find('.device-name').data('device-id');
                
                if (device_id) {
                    devices.push({'id': device_id});
                }
            }
            
            if (!devices.length) {
                hasErrors = true;
                a_messages.push({'type': 'fehler', 'message': '<?php echo $this->translate('tooltip_device_group_needs_device');?>'});
            }
            
            if (!hasErrors) {
                jQuery().setEditedElements('device_group_devices',   devices);
                jQuery().setEditedElements('device_group_id',        jQuery('#device_group_id').val());
                jQuery().setAjax(true);

                CADEditSave();
            } else {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init(a_messages);
                obj_cad_messages.open();
            }
        }
        edit_init(false);
        initDeviceGroupsEdit();
</script>
