<div style="position: relative;">
    <img src="/images/content/statisch/grafiken/close_button.png" 
         style="position: absolute; top: -25px; right: -30px;"
         onclick="jQuery(this).parent().parent().fadeOut();" />
<?php
    if(is_array($this->a_muskelgruppen_vorschlaege) &&
       count($this->a_muskelgruppen_vorschlaege) > 0)
    {
        foreach($this->a_muskelgruppen_vorschlaege as $a_muskelgruppe_vorschlag)
        {
            $this->assign($a_muskelgruppe_vorschlag);
            echo $this->render('muscle-groups/geraetegruppe-vorschlag-loop.phtml');
        }
    }
    else
    {
        echo "Leider wurden keine entsprechenden Muskeln gefunden!";
    }
?>
</div>