<?php
    if(isset($this->json_string))
    {
        echo $this->json_string;
    }
    else if(is_array($this->a_geraetegruppe_geraete) &&
            count($this->a_geraetegruppe_geraete) > 0)
    {
        foreach($this->a_geraetegruppe_geraete as $a_geraetegruppe_geraet)
        {
            $this->assign($a_geraetegruppe_geraet);
            echo $this->render('devices/device-edit.phtml');
        }
    }
    $this->assign('geraet_id', '');
    $this->assign('geraet_name', '');
    echo $this->render('devices/device-edit.phtml');
?>
<script type="text/javascript">
    initGeraetegruppenEdit();
</script>
