<?php
    if(is_array($this->a_geraetegruppen))
    {
        foreach($this->a_geraetegruppen as $a_geraetegruppe) {
            $this->assign($a_geraetegruppe);
            echo $this->render('loops/device-group.phtml');
        }
    }
?>

<script type="text/javascript">
    jQuery('document').ready(function()
    {
        jQuery('.device-group-delete').unbind('click').bind('click', function()
        {
            if(confirm('Diese Geraetegruppe wirklich löschen?\n\nAchtung:\n' +
                       'Wenn Sie diese Geraetegruppe löschen, werden auch alle ' +
                       'mit Ihr verknüpften Übungen gelöscht!'))
            {
                jQuery(this).deleteDeviceGroup();
            }
        });
        
        jQuery.fn.deleteDeviceGroup = function() {
            var deviceGroupId = jQuery(this).data('device-group-id');
            var that = this;
            
            if (isNumber(deviceGroupId)
               && 0 < deviceGroupId
            ) {
                var url = "/device-groups/delete-device-group/";
                var obj_params = {'id': deviceGroupId, 'ajax': true};
                
                jQuery.post(url, obj_params, function(response) {
                    try {
                        response = JSON.parse(response);
                        var cad_obj_messages = new CAD.Message();
                        cad_obj_messages.init(response);
                        
                        if(cad_obj_messages.open()) {
                            jQuery(that).parent().fadeOut();
                        }
                    } catch(e) {
                        alert(response);
                    }
                });
            } else {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init([{'type': 'fehler', 'message': 'Fehler bei der Übergabe!<br /><br />Ich kann diese Geraetegruppe leider nicht löschen!'}]);
                obj_cad_messages.open();
            }
        };
    });
</script>
