<form method="post" action="" id="login_form">
	<h3 style="margin-bottom: 10px;">
		Login auf byte-artist.de
	</h3>
	<input type="text" data-default="Ihre Login" name="user-login-name" id="user_login_name" value="" />
	<br class="clear-fix" />
	<input type="password" class="password" data-default="Ihr Passwort" title="Ihr Passwort" style="margin: 5px 0;"
           name="user-login-password" id="user_login_password" value="" />
	<br class="clear-fix" />
	<input type="submit" class="button" style="margin: 5px 0;" value=" einloggen " />
</form>
<div id="login_form_fail_options" >
	<a href="/auth/password-forgotten-form" id="password_forgotten" class="link" style="display: none; margin-top: 5px; clear: both; float: left;" >
		Passwort vergessen?
	</a>
	<a href="/auth/register-form" id="register" class="link" style="margin-top: 5px; clear: both; float: left; display: inline;" >
		noch nicht Registriert?
	</a>
</div>
<script type="text/javascript" src="/js/auth.js"></script>
