<div>
	<form method="post" action="" id="password_forgotten_form" >
		<label>
			Bitte geben Sie die E-Mail Adresse ein, mit der Sie sich auf www.byte-artist.de
			registriert haben.
		</label>
		<br />
		<input type="text" style="width: 200px; margin-top: 5px;" id="password_forgotten_email" name="password_forgotten_email" value="" />
		<br />
		<input type="submit" style="margin-top: 5px;" id="password_forgotten_submit" value=" Neues Passwort anfordern " />
	</form>
</div>
<script type="text/javascript">
	function passwordForgottenInit()
	{
		jQuery('#password_forgotten_form').submit(function(e)
		{
			e.preventDefault();
			
			var passwordForgottenEmail = jQuery('#password_forgotten_form #password_forgotten_email').val() != jQuery('#password_forgotten_form #password_forgotten_email').data('default') ? jQuery('#password_forgotten_form #password_forgotten_email').val() : '';

			if(trim(passwordForgottenEmail).length > 0)
			{
				var url = '/auth/password-forgotten/';
				var obj_params = {
                    'password_forgotten_email': Base64.encode(passwordForgottenEmail),
                    'ajax': true
                };
	
				jQuery.post(url, obj_params, function(response)
				{
//					var obj_cad_message = new CAD.Message();
//					obj_cad_message.init(response);

//					wenn daten erfolgreich gespeichert wurden
//					if(obj_cad_message.open())
//					{
//					}
					return false;
				});
			}
			else
			{
//				var obj_cad_message = new CAD.Message();
//				obj_cad_message.init([{'type': 'fehler', 'message': 'Bitte geben Sie eine E-Mail Adresse an!'}]);
//				obj_cad_message.open();
			}
		});

		prepareInputs();
	}

	passwordForgottenInit();
	
</script>