<div>
	<form method="post" action="" id="passwort-vergessen-form" >
		<label>
			Bitte geben Sie die E-Mail Adresse ein, mit der Sie sich auf www.byte-artist.de
			registriert haben.
		</label>
		<br />
		<input type="text" style="width: 200px; margin-top: 5px;" id="passwort_vergessen_email" name="passwort_vergessen_email" value="" />
		<br />
		<input type="submit" style="margin-top: 5px;" id="passwort_vergessen_submit" value=" Neues Passwort anfordern " />
	</form>
</div>
<script type="text/javascript">
	function passwort_vergessen_init()
	{
		jQuery('#passwort-vergessen-form').submit(function(e)
		{
			e.preventDefault();
			
			var passwort_vergessen_email = jQuery('#passwort-vergessen-form #passwort_vergessen_email').val() != jQuery('#passwort-vergessen-form #passwort_vergessen_email').data('default') ? jQuery('#passwort-vergessen-form #passwort_vergessen_email').val() : '';

			if(trim(passwort_vergessen_email).length > 0)
			{
				var url = '/auth/passwort-vergessen/';
				var obj_params = {	'passwort_vergessen_email': Base64.encode(passwort_vergessen_email),
									'ajax': true
								};
	
				jQuery.post(url, obj_params, function(response)
				{
					var obj_cad_message = new CAD.Message();
					obj_cad_message.init(response);

					// wenn daten erfolgreich gespeichert wurden
					if(obj_cad_message.open())
					{
					}
					return false;
				});
			}
			else
			{
				var obj_cad_message = new CAD.Message();
				obj_cad_message.init([{'type': 'fehler', 'message': 'Bitte geben Sie eine E-Mail Adresse an!'}]);
				obj_cad_message.open();
			}
		});

		prepareInputs();
	}

	passwort_vergessen_init();
	
</script>