<div id="register-wrapper" style="width: 520px;">
	<h2 style="text-align: center;">
		auf byte-artist.de einloggen
	</h2>
	<div class="register-rechts" 
		 style="float: left; display: inline; margin: 20px; width: 200px;">
		 <h3 style="margin-bottom: 10px;">
		 	über :
		 </h3>
		Facebook oder<br />
		Google oder<br />
		Twitter oder<br />
		<br class="clear-fix" />
	</div>
	<div class="register-links" 
		 style="float: left; display: inline; margin: 20px; padding-left: 20px; 
		 		width: 200px; border-left: 1px solid #CECECE;">
		<h3 style="margin-bottom: 10px;">
			oder registrieren :
		</h3>
		<form method="post" action="" id="register-form" >
			<input type="text" data-default="Vorname" id="register_vorname" name="register_vorname" type="text" value="" style="margin-top: 5px;" />
			<br />
			<input type="text" data-default="Nachname" id="register_nachname" name="register_nachname" type="text" value="" style="margin-top: 5px;" />
			<br />
			<input type="text" class="required" id="register_email" name="register_email" data-default="E-Mail *" type="text" value="" required="required" style="margin-top: 5px;" />
			<br />
			<input type="text" class="password required" id="register_passwort" name="register_passwort" data-default="Passwort *" type="text" value="" required="required" style="margin-top: 5px;" />
			<br />
			<input type="submit" id="register_submit" name="register_submit" value=" Registrieren " style="margin-top: 5px;" />
		</form>
		<br class="clear-fix" />
	</div>
	<br class="clear-fix" />
</div>
<script type="text/javascript">

	function initRegister()
	{
		jQuery('#register-form').submit(function(e)
		{
			e.preventDefault();
			
			var registerFirstName	= jQuery('#register_form #register_first_name').val() != jQuery('#register_form #register_first_name').data('default') ? jQuery('#register-form #register_first_name').val() : '';
			var registerName	    = jQuery('#register_form #register_name').val() != jQuery('#register_form #register_name').data('default') ? jQuery('#register-form #register_name').val() : '';
			var registerEmail 		= jQuery('#register_form #register_email').val() != jQuery('#register_form #register_email').data('default') ? jQuery('#register-form #register_email').val() : '';
			var registerPassword    = jQuery('#register_form #register_password').val() != jQuery('#register_form #register_password').data('default') ? jQuery('#register-form #register_password').val() : '';

			if(0 < trim(registerEmail).length
			   && 8 <= trim(registerPassword).length
            ) {
				var url = '/auth/register/';
				var obj_params = {	'register_first_name': Base64.encode(registerFirstName),
									'register_name': Base64.encode(registerName),
									'register_email': Base64.encode(registerEmail),
									'register_password': Base64.encode(registerPassword),
									'ajax': true
								};
	
				jQuery.post(url, obj_params, function(response) {
					var obj_cad_message = new CAD.Message();
					obj_cad_message.init(response);

					// wenn daten erfolgreich gespeichert wurden
					if(obj_cad_message.open()) {
						jQuery('#login_form #user_login_name').val(registerEmail);
						jQuery('#login_form #user_login_password').val(registerPassword);
					}
					return false;
				});
			}
			else if (0 == trim(registerEmail).length
                || 0 == trim(registerPassword).length
            ) {
				var obj_cad_message = new CAD.Message();
				obj_cad_message.init([{'type': 'fehler', 'message': 'Bitte füllen Sie alle mit "*" markierten Felder aus!'}]);
				obj_cad_message.open();
			} else if (8 < trim(registerPassword).length) {
				var obj_cad_message = new CAD.Message();
				obj_cad_message.init([{'type': 'fehler', 'message': 'das Passwort muss aus mindestens 8 Zeichen bestehen!'}]);
				obj_cad_message.open();
			}
		});

		prepareInputs();
	}
    initRegister();

</script>