<div id="register-wrapper" style="width: 520px;">
	<h2 style="text-align: center;">
		auf byte-artist.de einloggen
	</h2>
	<div class="register-rechts" 
		 style="float: left; display: inline; margin: 20px; width: 200px;">
		 <h3 style="margin-bottom: 10px;">
		 	über :
		 </h3>
		Facebook oder<br />
		Google oder<br />
		Twitter oder<br />
		<br class="clearfix" />
	</div>
	<div class="register-links" 
		 style="float: left; display: inline; margin: 20px; padding-left: 20px; 
		 		width: 200px; border-left: 1px solid #CECECE;">
		<h3 style="margin-bottom: 10px;">
			oder registrieren :
		</h3>
		<form method="post" action="" id="register-form" >
			<input type="text" data-default="Vorname" id="register_vorname" name="register_vorname" type="text" value="" style="margin-top: 5px;" />
			<br />
			<input type="text" data-default="Nachname" id="register_nachname" name="register_nachname" type="text" value="" style="margin-top: 5px;" />
			<br />
			<input type="text" class="required" id="register_email" name="register_email" data-default="E-Mail *" type="text" value="" required="required" style="margin-top: 5px;" />
			<br />
			<input type="text" class="password required" id="register_passwort" name="register_passwort" data-default="Passwort *" type="text" value="" required="required" style="margin-top: 5px;" />
			<br />
			<input type="submit" id="register_submit" name="register_submit" value=" Registrieren " style="margin-top: 5px;" />
		</form>
		<br class="clearfix" />
	</div>
	<br class="clearfix" />
</div>
<script type="text/javascript">

	function init_regsiter()
	{
		jQuery('#register-form').submit(function(e)
		{
			e.preventDefault();
			
			var register_vorname	= jQuery('#register-form #register_vorname').val() != jQuery('#register-form #register_vorname').data('default') ? jQuery('#register-form #register_vorname').val() : '';
			var register_nachname	= jQuery('#register-form #register_nachname').val() != jQuery('#register-form #register_nachname').data('default') ? jQuery('#register-form #register_nachname').val() : '';
			var register_email 		= jQuery('#register-form #register_email').val() != jQuery('#register-form #register_email').data('default') ? jQuery('#register-form #register_email').val() : '';
			var register_passwort 	= jQuery('#register-form #register_passwort').val() != jQuery('#register-form #register_passwort').data('default') ? jQuery('#register-form #register_passwort').val() : '';

			if(trim(register_email).length > 0 &&
			   trim(register_passwort).length >= 8)
			{
				var url = '/auth/register/';
				var obj_params = {	'register_vorname': Base64.encode(register_vorname),
									'register_nachname': Base64.encode(register_nachname),
									'register_email': Base64.encode(register_email),
									'register_passwort': Base64.encode(register_passwort),
									'ajax': true
								};
	
				jQuery.post(url, obj_params, function(response)
				{
					var obj_cad_message = new CAD.Message();
					obj_cad_message.init(response);

					// wenn daten erfolgreich gespeichert wurden
					if(obj_cad_message.open())
					{
						jQuery('#login_form #user_login_name').val(register_email);
						jQuery('#login_form #user_login_passwort').val(register_passwort);
					}
					return false;
				});
			}
			else if(trim(register_email).length == 0 ||
					trim(register_passwort).length == 0)
			{
				var obj_cad_message = new CAD.Message();
				obj_cad_message.init([{'type': 'fehler', 'message': 'Bitte füllen Sie alle mit "*" markierten Felder aus!'}]);
				obj_cad_message.open();
			}
			else if(trim(register_passwort).length < 8)
			{
				var obj_cad_message = new CAD.Message();
				obj_cad_message.init([{'type': 'fehler', 'message': 'das Passwort muss aus mindestens 8 Zeichen bestehen!'}]);
				obj_cad_message.open();
			}
		});

		prepareInputs();
	}
	init_regsiter();

</script>