<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 04.05.14
 * Time: 17:15
 */

?>

<ol class="training-plan droppable row ui-sortable"
    id="<?php echo $this->training_plan_id;?>">
    <a class="glyphicon glyphicon-edit" href="/training-plans/edit/id/<?php echo $this->training_plan_id;?>"
       style="width: 15px; position: absolute; top: 15px; font-size: 15px; right: 15px; z-index: 2;"
       data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_training_plan');?>" >
    </a>

    <div class="col-sm-12">
        <strong>
            <?php echo $this->training_plan_name;?>
        </strong>
    </div>

    <?php echo $this->exercisesContent;?>

    <input type="hidden" name="training-plan-id[<?php echo $this->training_plan_id;?>]" id="training_plan_id_<?php echo $this->training_plan_id;?>"
           value="<?php echo $this->training_plan_id;?>" />
    <li class="placeholder"></li>

<?php
    echo $this->musclesForExerciseContent;
?>
    <br class="clear-fix" />

    <a href="/training-diaries/start/id/<?php echo $this->training_plan_id;?>">
        <button class="btn btn-primary btn-default">
            <?php echo $this->translate('label_start_training_plan');?>
        </button>
    </a>
    <br class="clear-fix" />
</ol>
