<a name="right" ></a>

<div>
    <h3>
        <?php echo $this->translate('label_muscle_name');?>:
    </h3>
    <input type="text"
           class="form-control"
           value="<?php echo $this->muscle_name;?>"
           id="muscle_name" data-cad-cms-content-orig="<?php echo base64_encode($this->muscle_name);?>" />

    <br class="clear-fix"/>

    <input type="hidden" class="id" name="muscle-id" id="muscle_id" value="<?php echo $this->muscle_id; ?>"/>
</div>

<br class="clear-fix"/>

<button id="save" class="save btn btn-primary btn-block">
    <?php echo $this->translate('label_save');?>
</button>

<script type="text/javascript">
    jQuery('#save').unbind('click').click(function() {
        var hasErrors = false;
        var messages = '<ul>';

        if (!jQuery.trim(jQuery('#muscle_name').val()).length) {
            hasErrors = true;
            messages += '<li><?php echo $this->translate('tooltip_muscle_needs_name');?></li>';
        }

        if (!hasErrors) {
            var data = {
                muscle_id: jQuery('#muscle_id').val(),
                muscle_name: Base64.encode(jQuery('#muscle_name').val()),
                ajax: true
            };
            jQuery.post('/'+controller+'/save', data, function(response) {
                var json = JSON.parse(response);

                if (200 == json.state) {
                    showDialog(json.message, BootstrapDialog.TYPE_SUCCESS);
                } else {
                    showDialog(json.message, BootstrapDialog.TYPE_CRITICAL);
                }
            });
        } else {
            messages += '</ul>';
            showDialog(messages, BootstrapDialog.TYPE_CRITICAL);
        }
    });
</script>