<?php
    echo $this->musclesContent;
?>

<script type="text/javascript">
    jQuery('document').ready(function()
    {
        jQuery('.muscle-delete').unbind('click').bind('click', function() {
            if(confirm('Diesen Muskel wirklich löschen?\n\nAchtung:\n' +
                       'Wenn Sie diesen Muskel löschen, werden auch alle ' +
                       'mit Ihm verknüpften Muskelgruppen und Übungen gelöscht!')
            ) {
                jQuery(this).deleteMuscle();
            }
        });
        
        jQuery.fn.deleteMuscle = function() {
            var muscle_id = jQuery(this).data('muscle-id');
            var that = this;
            
            if (isNumber(muscle_id)
               && 0 < muscle_id
            ) {
                var url = "/muscles/delete-muscle/";
                var obj_params = {'id': muscle_id, 'ajax': true};
                
                jQuery.post(url, obj_params, function(response) {
                    try {
                        response = JSON.parse(response);
                        var cad_obj_messages = new CAD.Message();
                        cad_obj_messages.init(response);
                        
                        if (cad_obj_messages.open()) {
                            jQuery(that).parent().fadeOut();
                        }
                    }
                    catch(e)
                    {
                        alert(response);
                    }
                });
            } else {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init([{'type': 'fehler', 'message': 'Fehler bei der Übergabe!<br /><br />Ich kann diesen Muskel leider nicht löschen!'}]);
                obj_cad_messages.open();
            }
        };
    });
</script>
