<a name="right" ></a>

<div class="detail-options">
    <?php echo $this->detailOptionsContent;?>
</div>

<br class="clear-fix" />

<div class="col-sm-12" style="margin-top: 30px;">
    <?php echo $this->translate('label_muscle_name');?> : <?php echo $this->name;?>
</div>

<script type="text/javascript" language="JavaScript">
    jQuery(document).ready(function() {
        jQuery('.detail-options .edit-button').unbind('click').click(function() {
            loadEditContent(jQuery(this).data('id'));
        });
        jQuery('.detail-options .delete-button').unbind('click').click(function() {
            deleteEntry(jQuery(this).data('id'));
        });
    });
</script>
