<div id="register-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h1 class="text-center">Register now - it´s free!</h1>
            </div>
            <div class="modal-body">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="text-center">

                                <div class="panel-body">
                                    <fieldset>
                                        <div class="form-group">
                                            <input id="first_name" class="form-control input-lg" placeholder="First Name" name="first-name" type="text">
                                        </div>
                                        <div class="form-group">
                                            <input id="name" class="form-control input-lg" placeholder="Name" name="name" type="text">
                                        </div>
                                        <div class="form-group">
                                            <input id="email" class="form-control input-lg" placeholder="E-Mail" name="first-name" type="email">
                                        </div>
                                        <input id="send_register" class="btn btn-lg btn-primary btn-block" value="Register" type="submit">
                                    </fieldset>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-md-12">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#send_register').unbind('click').click(function() {
            jQuery.post('/auth/register/save', {
                ajax: true,
                register_email: Base64.encode(jQuery('#email').val()),
                register_first_name: Base64.encode(jQuery('#first_name').val()),
                register_last_name: Base64.encode(jQuery('#last_name').val()),

            }, function(response) {
                var json = JSON.parse(response);

                if (200 == json.state) {
                    window.modal.modal('toggle');
                    showDialog(json.message, BootstrapDialog.TYPE_SUCCESS);
                } else {
                    showDialog(json.message, BootstrapDialog.TYPE_WARNING);
                }
            });
        });
    });
</script>