<html lang="de" <?php if($this->obj_social_media){ echo $this->obj_social_media->getHtmlAttributes();}?> >
    <head <?php if($this->obj_social_media){ echo $this->obj_social_media->getHeadAttributes();}?> >
    	<?php echo $this->headMeta();?>
    	
        <?php echo $this->headTitle()->setSeparator(' | ')->setAutoEscape(false) ?>

		<?php echo $this->headLink();?>
		
		<?php echo $this->headScript();?>

    </head>
   <body itemscope itemtype="http://schema.org/Article" <?php if($this->obj_social_media){ echo $this->obj_social_media->getBodyAttributes();}?> >
    <div id="wrapper" data-role="page">
        <header>
	      <div id="login-container">
<?php
	$obj_user_identity = Zend_Auth::getInstance()->getIdentity();

	$obj_checkRecht = new Application_Plugin_CheckeRecht();

	if($obj_user_identity)
	{
?>
			<form method="post" action="" id="login_form">
				<span>Willkommen, <?php echo ucfirst($obj_user_identity->user_vorname);?> <?php echo ucfirst($obj_user_identity->user_nachname);?></span>
				<input type="hidden" name="user_logout" id="user_logout" value="1" />
				<input type="submit" id="logout-button" value=" Logout " />
			</form>
<?php
	}
	else
	{
?>
	      	<a href="/auth/login" id="login-button" >Login</a>
<?php
	}
?>
	      </div>
	    </header>
        <div class="container" >

            <div id="content">

                <?php  echo $this->layout()->content;?>

                <br class="clearfix" />
            </div> <!-- /container -->
            <br class="clearfix" />
        </div>

        <footer>

        </footer>
    </div>

	<div id="sperre"></div>

	<div id="dummy_container"></div>

	<div id="message">
		<div class="button_close" onclick="hideMessage(true);"></div>
		<div id="message_text"></div>
		<br class="clearfix" />
	</div>

	<div id="loader"></div>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>
