<html lang="de" <?php if($this->obj_social_media){ echo $this->obj_social_media->getHtmlAttributes();}?> >
    <head <?php if($this->obj_social_media){ echo $this->obj_social_media->getHeadAttributes();}?> >
    	<?php echo $this->headMeta();?>
    	
        <?php echo $this->headTitle()->setSeparator(' | ')->setAutoEscape(false) ?>

		<?php echo $this->headLink();?>
		
		<?php echo $this->headScript();?>

        <link rel="stylesheet" href="/css/jquery-mobile-slide-menu.css" type="text/css" />
        <script type="text/javascript" src="/js/jquery-mobile-slide-menu.js"></script>
    </head>
   <body itemscope itemtype="http://schema.org/Article" <?php if($this->obj_social_media){ echo $this->obj_social_media->getBodyAttributes();}?> >
    <div id="wrapper" data-role="page">
        <header>
	      <div id="login-container">
<?php
	$obj_user_identity = Zend_Auth::getInstance()->getIdentity();

	$obj_checkRecht = new Application_Plugin_CheckeRecht();

	if($obj_user_identity)
	{
?>
			<form method="post" action="" id="login_form">
				<span>Willkommen, <?php echo ucfirst($obj_user_identity->user_vorname);?> <?php echo ucfirst($obj_user_identity->user_nachname);?></span>
				<input type="hidden" name="user_logout" id="user_logout" value="1" />
				<input type="submit" id="logout-button" value=" Logout " />
			</form>
<?php
	}
	else
	{
?>
	      	<a href="/auth/login" id="login-button" >Login</a>
<?php
	}
?>
	      </div>
	    </header>
        <div class="container" >
            <div id="side-menu">
                <ul id="navi">
                    <li class="<?php if($this->controller == "handbuch"){ echo 'active';}?>">
                        <a href="/downloads/Rundumfit.pdf" target="_blank">
                            <span class="icon">Handbuch</span>
                        </a>
                    </li>
                    <li class="<?php if($this->controller == "muskeln"){ echo 'active';}?>">
                        <a href="/muskeln/">
                            <span class="icon">Muskeln</span>
                        </a>
                        <ul>
                            <li class="<?php if($this->controller == "muskeln" && $this->action == "index"){ echo 'active';}?>">
                                <a href="/muskeln/">
                                    Übersicht
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "muskeln" && $this->action == "edit"){ echo 'active';}?>">
                                <a href="/muskeln/edit/">
                                    Neu anlegen
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="<?php if($this->controller == "muskelgruppen"){ echo 'active';}?>">
                        <a href="/muskelgruppen/">
                            Muskelgruppen
                        </a>
                        <ul>
                            <li class="<?php if($this->controller == "muskelgruppen" && $this->action == "index"){ echo 'active';}?>">
                                <a href="/muskelgruppen/">
                                    Übersicht
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "muskelgruppen" && $this->action == "edit"){ echo 'active';}?>">
                                <a href="/muskelgruppen/edit/">
                                    Neu anlegen
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="<?php if($this->controller == "geraete"){ echo 'active';}?>">
                        <a href="/geraete/">
                            Geräte
                        </a>
                        <ul>
                            <li class="<?php if($this->controller == "geraete" && $this->action == "index"){ echo 'active';}?>">
                                <a href="/geraete/">
                                    Übersicht
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "geraete" && $this->action == "edit"){ echo 'active';}?>">
                                <a href="/geraete/edit/">
                                    Neu anlegen
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="<?php if($this->controller == "geraetegruppen"){ echo 'active';}?>">
                        <a href="/geraetegruppen/">
                            Gerätegruppen
                        </a>
                        <ul>
                            <li class="<?php if($this->controller == "geraetegruppen" && $this->action == "index"){ echo 'active';}?>">
                                <a href="/geraetegruppen/">
                                    Übersicht
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "geraetegruppen" && $this->action == "edit"){ echo 'active';}?>">
                                <a href="/geraetegruppen/edit/">
                                    Neu anlegen
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="<?php if($this->controller == "uebungen"){ echo 'active';}?>">
                        <a href="/uebungen/">
                            <span class="icon">Übungen</span>
                        </a>
                        <ul>
                            <li class="<?php if($this->controller == "uebungen" && $this->action == "index"){ echo 'active';}?>">
                                <a href="/uebungen">
                                    <span class="icon">Übersicht</span>
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "uebungen" && $this->action == "edit"){ echo 'active';}?>">
                                <a href="/uebungen/edit/">
                                    Neu anlegen
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="<?php if($this->controller == "trainingsplan"){ echo 'active';}?>">
                        <a href="/trainingsplan/">
                            Trainingsplan
                        </a>
                        <ul>
                            <li class="<?php if($this->controller == "trainingsplan" && $this->action == "index"){
                                echo 'active';}?>">
                                <a href="/trainingsplan">
                                    Übersicht
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "trainingsplan" && $this->action == "select-layout"){
                                echo 'active';}?>">
                                <a href="/trainingsplan/select-layout/">
                                    Neu anlegen
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "trainingsplan" && $this->action == "archiv"){
                                echo 'active';}?>">
                                <a href="/trainingsplan/archiv/">
                                    Archiv
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="<?php if($this->controller == "trainingstagebuch"){ echo 'active';}?>">
                        <a href="/trainingstagebuch/">
                            Trainingstagebuch
                        </a>
                        <ul>
                            <li class="<?php if($this->controller == "trainingstagebuch" && $this->action == "index"){
                                echo 'active';}?>">
                                <a href="/trainingstagebuch">
                                    Übersicht
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "trainingstagebuch" && $this->action == "edit"){
                                echo 'active';}?>">
                                <a href="/trainingstagebuch/edit/">
                                    Neu anlegen
                                </a>
                            </li>
                            <li class="<?php if($this->controller == "trainingstagebuch" && $this->action == "archiv"){
                                echo 'active';}?>">
                                <a href="/trainingstagebuch/archiv/">
                                    Archiv
                                </a>
                            </li>
                        </ul>
                    </li>
                    <br class="clearfix" />
                </ul>
            </div>

            <div data-url="demo-page" data-role="page" id="demo-page" data-theme="d">
                <div data-role="header" data-theme="b">
                    <h1>Swipe left or right</h1>
                    <a href="#left-panel" data-theme="d" data-icon="arrow-r" data-iconpos="notext" data-shadow="false" data-iconshadow="false" class="ui-icon-nodisc">Open left panel</a>
                    <a href="#right-panel" data-theme="d" data-icon="arrow-l" data-iconpos="notext" data-shadow="false" data-iconshadow="false" class="ui-icon-nodisc">Open right panel</a>
                </div><!-- /header -->
                <div data-role="content">
                    <dl>
                        <dt>Swipe <span>verb</span></dt>
                        <dd><b>1.</b> to strike or move with a sweeping motion</dd>
                    </dl>
                    <a href="#demo-intro" data-rel="back" class="back-btn" data-role="button" data-mini="true" data-inline="true" data-icon="back" data-iconpos="right">Back to demo intro</a>
                </div><!-- /content -->
                <div data-role="panel" id="left-panel" data-theme="b">
                    <p>Left reveal panel.</p>
                    <a href="#" data-rel="close" data-role="button" data-mini="true" data-inline="true" data-icon="delete" data-iconpos="right">Close</a>
                </div><!-- /panel -->
                <div data-role="panel" id="right-panel" data-display="push" data-position="right" data-theme="c">
                    <p>Right push panel.</p>
                    <a href="#" data-rel="close" data-role="button" data-mini="true" data-inline="true" data-icon="delete" data-iconpos="right">Close</a>
                </div><!-- /panel -->
            </div>

<!--            <div data-role="page" id="about-the-band" data-title="Page Title" data-theme="b" class="pages">-->
<!--                <div data-role="header" data-theme="b">-->
<!--                    <a href="#" class="showMenu" data-role="button" data-icon="grid" data-iconpos="notext">Menu</a>-->
<!--                    <h1>Header</h1>-->
<!--                </div>-->
<!---->
<!--                <div data-role="content">-->
<!--                    <p>Content Goes Here</p>-->
<!--                </div>-->
<!--            </div>-->

            <div id="content">

                <?php  echo $this->layout()->content;?>

                <br class="clearfix" />
            </div> <!-- /container -->
            <br class="clearfix" />
        </div>

        <footer>

        </footer>
    </div>


	<div id="sperre"></div>

	<div id="dummy_container"></div>

	<div id="message">
		<div class="button_close" onclick="hideMessage(true);"></div>
		<div id="message_text"></div>
		<br class="clearfix" />
	</div>

	<div id="loader"></div>
	
    <script type="text/javascript">
//    	init();
/*
		var nextpage = null;
		var prevpage = null;

		$('.swipe').swiperight(function()
		{
		     $('#navi').fadeIn();
		});

		$('.swipe').swipeleft(function()
		{
		     $('#navi').fadeOut();
		});

		$('body').swipeleft(function()
		{
			var next_page = $('#navi li.aktiv').next('li').find('a').attr("href");
			console.log($('#navi li.aktive').next('li'));

			if(undefined != next_page &&
			   next_page.length)
			{
				$.mobile.loadPage(next_page,
				{
//					'pageContainer': $('html'),
					 'type': "post",
//					 data: $("form#search").serialize()
				}).done(function()
				{
					$('#wrapper').replaceWith(arguments[2]);
				});
			}
		});

		$('body').swiperight(function()
		{
			var prev_page = $('#navi li.aktiv').prev('li').find('a').attr("href");

			if(undefined != prev_page &&
			   prev_page.length)
			{
				$.mobile.loadPage(prev_page,
				{
//					'pageContainer': $('html'),
					 'type': "post",
//					 data: $("form#search").serialize()
				}).done(function()
				{
					$('#wrapper').replaceWith(arguments[2]);
				});
			}
		});

		$(document).ready(function()
		{
			$('a').unbind('click');
//			$('#navi .tooltip_target').unbind('click');
			$('a').bind('click', function()
			{
				var url = $(this).attr('href');
				location.href = url;

//				$.mobile.loadPage($(this).attr('href'),
//				{
////					'pageContainer': $('html'),
//					 'type': "post",
////					 data: $("form#search").serialize()
//				}).done(function()
//				{
//					console.log(arguments);
//					$('#wrapper').replaceWith(arguments[2]);
//				});
//			});

		});
*/
    $(function(){
        $('#side-menu').slideMenu();
    });

    $( document ).on( "pageinit", "#demo-page", function() {
        $( document ).on( "swipeleft swiperight", "#demo-page", function( e ) {
            // We check if there is no open panel on the page because otherwise
            // a swipe to close the left panel would also open the right panel (and v.v.).
            // We do this by checking the data that the framework stores on the page element (panel: open).
            if ( $.mobile.activePage.jqmData( "panel" ) !== "open" ) {
                if ( e.type === "swipeleft"  ) {
                    $( "#right-panel" ).panel( "open" );
                } else if ( e.type === "swiperight" ) {
                    $( "#left-panel" ).panel( "open" );
                }
            }
        });
    });

    </script>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
