<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 01.05.14
 * Time: 19:22
 */ 
?>

<div class="row">
    <div class="col-sm-12">
        <?php echo $this->userSelect;?>
    </div>

    <div class="col-sm-12">
        Trainingsplan Layout für einen neuen Trainingsplan auswählen :
        <div class="form-group">

            <div class="checkbox checkbox-primary">
                <label class="custom-control custom-radio">
                    <input id="layout1" name="layout" type="radio" class="custom-control-input" value="1">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description"><?php echo $this->translate('label_normal_training_plan');?></span>
                </label>
            </div>

            <div class="checkbox checkbox-primary">
                <label class="custom-control custom-radio">
                    <input id="layout2" name="layout" type="radio" class="custom-control-input" value="2">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description"><?php echo $this->translate('label_split_training_plan');?></span>
                </label>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <?php echo $this->translate('or') . ' ' . $this->translate('select_existing_training_plan_as_template');?> :
        <?php echo $this->trainingPlanSelect;?>
    </div>

    <div class="col-sm-12">
        <button class="btn btn-primary btn-block save" style="margin-top: 20px;">
            create
        </button>
    </div>
</div>

<script type="text/javascript" language="JavaScript">
    jQuery('document').ready(function(){

        jQuery('body').css('overflow', 'auto');
        initTrainingPlanSelect();

        var trainingSelectAjax = null;

        jQuery('.save').unbind('click').click(function() {
            jQuery(this).addClass('disabled');

            if (!jQuery('input[name=layout]:checked').val()
                && !jQuery('.training-plan-select').data('value')
            ) {
                showDialog("Es muss entweder ein Layout für einen neuen Trainingsplan,<br /><br />" +
                    "oder ein bestehender als Vorlage ausgewählt werden!", BootstrapDialog.TYPE_DANGER);
                jQuery(this).removeClass('disabled');
                return false;
            }
            data = {
                ajax: true,
                trainingPlanUserId: jQuery('.member-select').data('value'),
                trainingPlanLayoutId: jQuery('input[name=layout]:checked').val(),
                templateTrainingPlanId: jQuery('.training-plan-select').data('value')
            };
            trainingSelectAjax = jQuery.post('/'+controller+'/new', data, function(response) {
                var json = JSON.parse(response);
                if (200 == json.state) {
                    showDialog(json.message, BootstrapDialog.TYPE_SUCCESS);
                    window.location.href = '/'+controller+'/edit/id/' + json.id;
                } else {
                    showDialog(json.message, BootstrapDialog.TYPE_DANGER);
                }
            });
        });

        jQuery('.member-select .option-add').unbind('click').bind('click', function() {
            var selectedOption = jQuery(this).data('value');
            var selectedOptionName = jQuery(this).html();
            var caretContent = '<span class="caret"></span>';

            jQuery(this).parent().parent().parent().attr('data-value', selectedOption);
            jQuery(this).parent().parent().parent().find('.dropdown-toggle').html(selectedOptionName + caretContent).dropdown('toggle');
            jQuery(this).parent().parent().parent().find('#user_id').val(selectedOption);

            refreshTrainingPlanSelect();

            return false;
        });

        function initTrainingPlanSelect() {

            jQuery('.training-plan-select .option-add').unbind('click').bind('click', function () {
                var selectedOption = jQuery(this).data('value');
                var selectedOptionName = jQuery(this).html();
                var caretContent = '<span class="caret"></span>';

                jQuery(this).parent().parent().parent().attr('data-value', selectedOption);
                jQuery(this).parent().parent().parent().find('.dropdown-toggle').html(selectedOptionName + caretContent).dropdown('toggle');

                return false;
            });
        }

        function refreshTrainingPlanSelect() {

            if (trainingSelectAjax) {
                trainingSelectAjax.abort();
            }

            var trainingPlanSelect = jQuery('.training-plan-select');

            trainingSelectAjax = jQuery.ajax({
                url: '/' + controller + '/get-training-plan-select',
                data: {
                    user_id: jQuery('.member-select').attr('data-value'),
                    ajax: true,
                    format: 'json'
                },
                beforeSend: function () {
                    showSpinner(trainingPlanSelect);
                },
                error: function () {
                },
                success: function (response) {
                    jQuery(trainingPlanSelect).html('');
                    var json = JSON.parse(response);

                    if (200 == json.state) {
                        trainingPlanSelect.replaceWith(Base64.decode(json.htmlContent));
                        initTrainingPlanSelect();
                    } else {
                        var modal = jQuery('#modal');
                        considerResponseCodeForModal(json.state);
                        jQuery('#modal_save').hide();
                        jQuery('.modal-body').html('<p>' + json.message + '</p>');
                        modal.modal();
                    }
                },
                always: function () {
                    accordionAjaxRequest = null;
                },
                type: 'POST'
            });
        }
    });
</script>
