<a name="right" />
<div>
    <a href="/training-plans/edit/id/<?php echo $this->training_plan_id;?>">
        <button class="btn btn-primary btn-default" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_training_plan');?>">
            <?php echo $this->translate('label_edit_training_plan');?>
        </button>
    </a>
    <?php
        echo $this->trainingPlanContent;
    ?>
</div>
