<?php
    $obj_cad_filter_ubb_replace = new CAD_Filter_UbbReplace();
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div>
    <h3>
        <?php echo $this->translate('label_exercise_name');?>:
        <span
            class="editable col-md-12"
            style="margin-left: 20px; border-bottom: 1px dotted gray;"
            id="exercise_name" data-cad-cms-content-orig="<?php echo base64_encode($this->exercise_name);?>"
            data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_exercise_name');?>"
		><?php echo $obj_cad_filter_ubb_replace->filter($this->exercise_name);?>
        </span>
    </h3>

    <?php echo $this->previewPictureContent;?>

    <br class="clear-fix" style="margin-top: 15px;" />

    <?php echo $this->exerciseTypeSelectContent;?>

    <br class="clear-fix" />

    <h3 class=""
        style="margin-top: 15px;">
        <?php echo $this->translate('label_description');?>:
    </h3>
    
    <br class="clear-fix" />
    
    <div class="editable beschreibung col-md-12"
         id="exercise_description"
         style="margin-top: 5px; border-bottom: 1px dotted gray;"
         data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_description');?>"
         data-cad-cms-content-orig="<?php echo base64_encode($this->exercise_description);?>" >
        <?php echo $obj_cad_filter_ubb_replace->filter($this->exercise_description);?>
    </div>
    
    <br class="clear-fix" />
    
    <h3 class="besonderheit-ueberschrift"
        style="margin-top: 15px;">
        <?php echo $this->translate('label_special_features');?>:
    </h3>
    
    <br class="clear-fix" />

    <div class="row">
        <div class="editable beschreibung col-md-12"
            id="exercise_special_features"
            style="margin-top: 5px; border-bottom: 1px dotted gray;"
            data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_special_features');?>"
            data-cad-cms-content-orig="<?php echo base64_encode($this->exercise_special_features);?>" >
            <?php echo $obj_cad_filter_ubb_replace->filter($this->exercise_special_features);?>
        </div>
    </div>

    <br class="clear-fix" />

    <h3 style="margin-top: 25px;">
        <?php echo $this->translate('label_device');?>:
    </h3>

    <br class="clear-fix" />

    <div class="form-group" style="margin-top: 10px;">
        <input type="text" class="form-control device-name"
               id="exercise_device_name"
               name="exercise_device_name"
               value="<?php echo $this->device_name;?>"
               data-exercise-device-name="<?php echo base64_encode($this->device_name);?>"
               data-exercise-device-id="<?php echo $this->device_id;?>"
               data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_type_to_get_device_proposals');?>"
            />
    </div>

    <br class="clear-fix" />

    <div style="float: left; display: inline;">
        <?php echo $this->deviceOptionsDropDownContent;?>
    </div>

    <br class="clear-fix" />

    <div class="device-options" style="margin-top: 25px;">
        <?php echo $this->deviceOptionsContent;?>
    </div>

    <br class="clear-fix" />

    <div style="float: left; display: inline; margin-top: 25px;">
        <?php echo $this->exerciseOptionsDropDownContent;?>
    </div>

    <br class="clear-fix" />

    <div class="exercise-options" style="margin-top: 25px;">
        <?php echo $this->exerciseOptionsContent;?>
    </div>

    <br class="clear-fix" />

    <h3 style="float: left; display: inline; margin-top: 25px;">
        <?php echo $this->translate('label_muscle_groups');?>:
    </h3>

    <br class="clear-fix" />

    <div class="form-group" style="margin-top: 15px;">
        <input class="form-control muscle-group-name"
               value=""
               data-muscle-group-name=""
               data-muscle-group-id=""
               type="text"
               data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_type_to_get_muscle_or_muscle_group_proposals');?>"
            >
    </div>

<!--    <img class="muscle-group-add" src="/images/content/statisch/grafiken/add_normal.png"-->
<!--         style="width: 30px; float: left; display: inline; margin-top: 15px;"/>-->
    
    <br class="clear-fix" />
    
    <div class="exercise-muscle-groups"
         style="margin-top: 5px;">
        <?php echo $this->exerciseMuscleGroupsContent;?>
    </div>
    
    <br class="clear-fix" />
    
    <h3 style="margin-top: 15px;">
        <?php echo $this->translate('label_exercise_pictures');?>:
    </h3>
    
    <div class="preview-pictures"
         style="margin-top: 5px;">
        <?php echo $this->previewPicturesContent;?>
    </div>
    
    <br class="clear-fix" />
    
    <h3 style="margin-top: 15px;">
        <?php echo $this->translate('label_exercise_video');?>:
    </h3>
    
    <div id="exercise_video"
         style="margin-top: 5px;">
        
    </div>
    <input type="hidden" class="id" name="exercise_id" id="exercise_id" value="<?php echo $this->exercise_id;?>" />
</div>

<br class="clear-fix" />

<input type="hidden" id="picture_path" value="<?php echo base64_encode($this->picturePath);?>" />
<input type="hidden" id="picture_temp_path" value="<?php echo base64_encode($this->pictureTempPath);?>" />
<input type="hidden" id="exercise_id" value="<?php echo $this->exercise_id;?>" />

<div class="proposals"
     style="position: absolute; left: -5000px; top: -5000px; padding: 10px;
            background-color: #FFFFFF; opacity: 0.9; box-shadow: 5px 5px 5px #111111;" ></div>

<button class="save button btn btn-primary btn-block">
    <?php echo $this->translate('label_save');?>
</button>

<script type="text/javascript">
	controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

	function save() {
        var hasErrors = false;
        var messages = [];
        var i = 0;

        if (!trim(jQuery('#exercise_name').html()).length) {
            hasErrors = true;
            messages.push({'type': 'fehler', 'message': '<?php echo $this->translate('tooltip_exercise_needs_name');?>'});
        }

        if (!trim(jQuery('#exercise_description').html()).length) {
            hasErrors = true;
            messages.push({'type': 'fehler', 'message': 'Die Beschreibung der Übung fehlt!'});
        }

        var currentMuscleGroups = jQuery('.exercise-muscle-groups').find('.muscle-group');
        var muscleGroups = [];

        // alle muskelgruppen durchlaufen
        for (i = 0, len = currentMuscleGroups.length; i < len; i++) {
            var muscles = [];
            var muscleGroupId = jQuery(currentMuscleGroups[i]).data('muscle-group-id');
            var currentMusclesInMuscleGroup = jQuery(currentMuscleGroups[i]).find('.muscle');

            for (var k = 0; k < currentMusclesInMuscleGroup.length; k++) {
                var muscleId = jQuery(currentMusclesInMuscleGroup[k]).data('muscle-id');
                var muscleUse = jQuery(currentMusclesInMuscleGroup[k]).find('.muscle-use').data('muscle-use');
                if (muscleId) {
                    muscles.push({'id': muscleId, 'muscle_use': muscleUse});
                }
            }
            if (muscleGroupId) {
                muscleGroups.push({'id': muscleGroupId, 'muscles': muscles});
            }
        }

        if (!muscleGroups.length) {
            hasErrors = true;
            messages.push({'type': 'fehler', 'message': 'Es muss mindestens eine Muskelgruppe für diese Übung vollständig ausgefüllt sein!'});
        }

        var currentDeviceOptions = jQuery('.device-options').find('.device-option');
        var deviceOptions = [];

        for (i = 0, len = currentDeviceOptions.length; i < len; i++) {
            var deviceOptionValue = jQuery(currentDeviceOptions[i]).val();
            var deviceOptionId = jQuery(currentDeviceOptions[i]).data('device-option-id');
            var deviceXDeviceOptionId = jQuery(currentDeviceOptions[i]).data('device-x-device-option-id');
            var exerciseXDeviceOptionId = jQuery(currentDeviceOptions[i]).data('exercise-x-device-option-id');
            var trainingPlanXDeviceOptionId = jQuery(currentDeviceOptions[i]).data('training-plan-x-device-option-id');
            var trainingDiaryXDeviceOptionId = jQuery(currentDeviceOptions[i]).data('training-diary-x-device-option-id');

            if (deviceOptionId) {
                deviceOptions.push({
                    deviceOptionId: deviceOptionId,
                    deviceXDeviceOptionId: deviceXDeviceOptionId,
                    exerciseXDeviceOptionId: exerciseXDeviceOptionId,
                    trainingPlanXDeviceOptionId: trainingPlanXDeviceOptionId,
                    trainingDiaryXDeviceOptionId: trainingDiaryXDeviceOptionId,
                    value: deviceOptionValue});
            }
        }

        var currentExerciseOptions = jQuery('.exercise-options').find('.exercise-option');
        var exerciseOptions = [];

        for (i = 0, len = currentExerciseOptions.length; i < len; i++) {
            var exerciseOptionValue = jQuery(currentExerciseOptions[i]).val();
            var exerciseOptionId = jQuery(currentExerciseOptions[i]).data('exercise-option-id');
            var exerciseXExerciseOptionId = jQuery(currentExerciseOptions[i]).data('exercise-x-exercise-option-id');
            var trainingDiaryXExerciseOptionId = jQuery(currentExerciseOptions[i]).data('training-diary-x-exercise-option-id');
            var trainingPlanXExerciseOptionId = jQuery(currentExerciseOptions[i]).data('training-plan-x-exercise-option-id');

            if (exerciseOptionId) {
                exerciseOptions.push({
                    exerciseOptionId: exerciseOptionId,
                    exerciseXExerciseOptionId: exerciseXExerciseOptionId,
                    trainingPlanXExerciseOptionId: trainingPlanXExerciseOptionId,
                    trainingDiaryXExerciseOptionId: trainingDiaryXExerciseOptionId,
                    value: exerciseOptionValue});
            }
        }

        if (!hasErrors) {
            jQuery().setEditedElements('exercise_muscle_groups', muscleGroups);
            jQuery().setEditedElements('exercise_preview_picture', jQuery('#exercise_preview_picture').data('file'));
            jQuery().setEditedElements('exercise_type_id', jQuery('.exercise-type-select').data('value'));
            jQuery().setEditedElements('exercise_options', exerciseOptions);
            jQuery().setEditedElements('exercise_device_options', deviceOptions);
            jQuery().setEditedElements('exercise_id', jQuery('#exercise_id').val());
            jQuery().setEditedElements('exercise_device_fk', jQuery('#exercise_device_name').data('exercise-device-id'));
            jQuery().setAjax(true);

            CADEditSave();
        } else {
            var obj_cad_messages = new CAD.Message();
            obj_cad_messages.init(messages);
            obj_cad_messages.open();
        }
    }

    jQuery(document).ready(function() {
//        jQuery('.exercise-type-select .option-add').unbind('click').bind('click', function() {
//            var selectedOption = jQuery(this).data('value');
//            var selectedOptionName = jQuery(this).html();
//            var caretContent = '<span class="caret"></span>';
//
//            jQuery(this).parent().parent().parent().attr('data-value', selectedOption);
//            jQuery(this).parent().parent().parent().find('.dropdown-toggle').html(selectedOptionName + caretContent).dropdown('toggle');
//
//            return false;
//        });

        jQuery('.dropdown.custom-drop-down .option-add').unbind('click').click(function() {
            var selectedOption = jQuery(this).data('value');
            var selectedOptionName = jQuery(this).html();
            var caretContent = '<span class="caret"></span>';

            jQuery(this).parent().parent().parent().attr('data-value', selectedOption);
            jQuery(this).parent().parent().parent().find('.dropdown-toggle').html(selectedOptionName + caretContent).dropdown('toggle');

            return false;
        });

        jQuery('.device-option-select .option-add').unbind('click').bind('click', function() {

            // check if selected option already exists
            var selectedOption = jQuery(this).data('value');
            var currentOptionsList = jQuery('.device-options').find('.device-option');

            for (var i = 0, len = currentOptionsList.length; i < len; i++) {
                var option_id = jQuery(currentOptionsList[i]).data('device-option-id');

                if (option_id == selectedOption) {
                    var obj_cad_messages = new CAD.Message();
                    obj_cad_messages.init([
                        {
                            'type': 'fehler',
                            'message': '<?php echo $this->translate('tooltip_selected_option_already_set');?>',
                            'confirm_func': "jQuery('#" + jQuery(currentOptionsList[i]).attr('id') + "').effect('highlight', {}, 5000)"
                        }
                    ]);
                    obj_cad_messages.open();

                    return false;
                }
            }

            jQuery(this).parent().parent().parent().find('.dropdown-toggle').dropdown('toggle');

            jQuery.post('/devices/get-device-option-edit', {ajax: true, device_option_id: selectedOption}, function(response) {
                jQuery('.device-options').append(response);
            });
            return false;
        });

        jQuery('.exercise-option-select .option-add').unbind('click').bind('click', function () {

            // check if selected option already exists
            var selectedOption = jQuery(this).data('value');
            var currentOptionsList = jQuery('.exercise-options').find('.exercise-option');

            for (var i = 0, len = currentOptionsList.length; i < len; i++) {
                var option_id = jQuery(currentOptionsList[i]).data('exercise-option-id');

                if (option_id == selectedOption) {
                    var obj_cad_messages = new CAD.Message();
                    obj_cad_messages.init([
                        {
                            'type': 'fehler',
                            'message': '<?php echo $this->translate('tooltip_selected_option_already_set');?>',
                            'confirm_func': "jQuery('#" + jQuery(currentOptionsList[i]).attr('id') + "').effect('highlight', {}, 5000)"
                        }
                    ]);
                    obj_cad_messages.open();

                    return false;
                }
            }

            jQuery(this).parent().parent().parent().find('.dropdown-toggle').dropdown('toggle');

            jQuery.post('/exercises/get-exercise-option-edit', {
                ajax: true,
                exercise_option_id: selectedOption,
                exercise_id: jQuery('#exercise_id').val()
            }, function (response) {
                jQuery('.exercise-options').append(response);
            });
            return false;
        });

        jQuery('.muscle-group-name').each(function() {
            var post_request = null;

            jQuery(this).unbind('keyup').on('keyup', function (e) {
                var url = '/muscle-groups/get-muscle-group-proposals/';
                var search = Base64.encode(jQuery(this).val());
                var self = jQuery(this);

                jQuery(self).css('background-color', 'red');
                jQuery(self).data('muscle-group-name', '');
                jQuery(self).data('muscle-group-id', '');

                if (null !== post_request) {
                    post_request.abort();
                }

                post_request = jQuery.ajax({
                    type: "POST",
                    url: url,
                    data: "search=" + search + "&ajax=true",
                    success: function (response) {
                        var offset = jQuery(self).offset();
                        jQuery('body').append(jQuery('.proposals'));
                        jQuery('.proposals').html(response)
                            .css('left', offset.left + "px")
                            .css('top', offset.top + 40 + "px");

                        jQuery('.proposals').find('.proposal').unbind('click').bind('click', function () {
                            // check ob diese muskelgruppe bereits gesetzt wurde
                            var vorhandene_muskelgruppen = jQuery('.exercise-muscle-groups').find('.muscle-group');

                            for (var i = 0, len = vorhandene_muskelgruppen.length; i < len; i++) {
                                if (jQuery(vorhandene_muskelgruppen[i]).find('.muscle-group-name').data('muscle-group-id') ==
                                    jQuery(this).data('proposal-id')
                                ) {
                                    var a_messages = new Array({
                                        'type': 'fehler',
                                        'message': 'Diese Muskelgruppe ist bereits gesetzt!'
                                    });
                                    var obj_cad_message = new CAD.Message();
                                    obj_cad_message.init(a_messages);
                                    obj_cad_message.open();

                                    return false;
                                }
                            }

                            addMuscleGroup(jQuery(this).data('proposal-id'), jQuery('#exercise_id').val());
                            jQuery('.proposals').fadeOut();
                            return false;
                        });
                        jQuery('.proposals').fadeIn();
                    }
                });
            });
        });

        edit_init(true);
        initDevicesEdit();
        initMuscleRating();
    });

    function addMuscleGroup(muscleGroupId, exerciseId) {
        jQuery.ajax({
            type: "POST",
            url: '/exercises/get-muscle-group-for-exercise-edit/',
            data: "muscle_group_id=" + muscleGroupId + "&exercise_id=" + exerciseId + "&ajax=true",
            success: function (response) {
                jQuery('.exercise-muscle-groups').append(response);
                initMuscleRating();
            }
        });
    }

    function initMuscleRating() {
        jQuery('.exercise-muscle-groups').find('.muscle-use').unbind('mouseover').unbind('mouseout').unbind('click').hover(
            function() {
                var x = null;
                jQuery(this).unbind('mousemove').mousemove(function (e) {
                    if (!jQuery(this).parent().parent().hasClass('deactivated')) {
                        var parentOffset = jQuery(this).parent().offset();
                        x = -100 + ( parseFloat(e.pageX) - parentOffset.left);
                        x = Math.round(x / 20) * 20;
                        jQuery(this).css('background-position', x + "px " + x + "px");
                    }
                });

                jQuery(this).unbind('click').click(function () {
                    if (!jQuery(this).parent().parent().hasClass('deactivated')) {
                        jQuery(this).data('background-position', x + "px " + x + "px");
                        jQuery(this).data('muscle-use', Math.round(5 + (x / 20)));
                        jQuery(this).css('background-position', jQuery(this).data('background-position'));
                        jQuery(this).attr('title', Math.round(5 + (x / 20)));
                    }
                });
            },
            function() {
                if (!jQuery(this).parent().parent().hasClass('deactivated')) {
                    if (undefined !== jQuery(this).data('background-position')) {
                        jQuery(this).css('background-position', jQuery(this).data('background-position'));
                    } else {
                        jQuery(this).css('background-position', '-100px 0');
                    }
                }
            }
        );

        jQuery('.muscle-delete').unbind('click').bind('click', function () {
            if (jQuery(this).parent().hasClass('deactivated')) {
                jQuery(this).parent().find('.muscle-use').css('background-position', jQuery(this).parent().find('.muscle-use').data('background-position'))
                    .data('muscle-use', jQuery(this).parent().find('.muscle-use').attr('data-muscle-use-before-delete'))
                    .attr('data-muscle-use-before-delete', 0);
                jQuery(this).parent().removeClass('deactivated');
            } else {
                jQuery(this).parent().find('.muscle-use')
                    .css('background-position', '-100px -100px')
                    .attr('data-muscle-use-before-delete', jQuery(this).parent().find('.muscle-use').data('muscle-use'))
                    .data('muscle-use', 0)
                    .parent().parent().addClass('deactivated');
            }
        });
    }

    function deleteMuscleGroup() {
        jQuery(obj_ref).data('muscle-group-name', '');
        jQuery(obj_ref).data('muscle-group-id', '');
        jQuery(obj_ref).fadeOut();
    }
</script>
