<h2>
    <?php echo $this->translate('label_exercises');?>
</h2>
<div class="col-sm-12 exercises-overview">
<?php
    if (is_array($this->a_uebungen)) {
        foreach($this->a_uebungen as $a_uebung) {
            $this->assign($a_uebung);
            echo $this->render('loops/exercise.phtml');
        }
    }
?>
</div>

<script type="text/javascript">
    jQuery('document').ready(function() {
        jQuery('.exercise-delete').unbind('click').click(function() {
            if(confirm('<?php echo $this->translate('question_warning_delete_exercise');?>')) {
                jQuery(this).loescheUebung();
            }
        });
        
        jQuery.fn.deleteExercise = function() {
            var exerciseId = jQuery(this).data('exercise-id');
            var that = this;
            
            if(isNumber(exerciseId)
                && 0 < exerciseId
            ) {
                var url = "/exercises/delete-exercise/";
                var obj_params = {'id': exerciseId, 'ajax': true};
                
                jQuery.post(url, obj_params, function(response) {
                    try {
                        response = JSON.parse(response);
                        var cad_obj_messages = new CAD.Message();
                        cad_obj_messages.init(response);
                        
                        if(cad_obj_messages.open()) {
                            jQuery(that).parent().fadeOut();
                        }
                    } catch(e) {
                        alert(response);
                    }
                });
            } else {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init([{'type': 'fehler', 'message': '<?php echo $this->translate('tooltip_cant_delete_exercise');?>'}]);
                obj_cad_messages.open();
            }
        };
    });
</script>