<div class="col-lg-6 exercises-overview" id="left">
    <div class="col-sm-4 exercises-filter">
        <?php echo $this->exercisesFilterContent;?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->deviceFilterContent;?>
    </div>
    <div class="col-sm-2">
        <button class="btn btn-primary btn-default search">
            <?php echo $this->translate('label_search');?>
        </button>
    </div>

    <br class="clear-fix" />
<?php
    if (is_array($this->exercisesCollection)) {
        foreach($this->exercisesCollection as $exercise) {
            $this->assign($exercise);
            echo $this->render('loops/exercise-row.phtml');
        }
    }
?>

</div>
<div class="col-lg-6" id="right">
    <?php echo $this->translate('exercises_default_content');?>
</div>

<!--<script type="text/javascript" src="/js/purl.js"></script>-->

<script type="text/javascript">
    controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

    jQuery('document').ready(function() {
        jQuery('.exercise-delete').unbind('click').click(function() {
            if(confirm('<?php echo $this->translate('question_warning_delete_exercise');?>')) {
                jQuery(this).deleteExercise();
            }
        });
        
        jQuery.fn.deleteExercise = function() {
            var exerciseId = jQuery(this).data('exercise-id');
            var that = this;
            
            if(isNumber(exerciseId)
                && 0 < exerciseId
            ) {
                var url = "/exercises/delete-exercise/";
                var obj_params = {'id': exerciseId, 'ajax': true};
                
                jQuery.post(url, obj_params, function(response) {
                    try {
                        response = JSON.parse(response);
                        var cad_obj_messages = new CAD.Message();
                        cad_obj_messages.init(response);
                        
                        if(cad_obj_messages.open()) {
                            jQuery(that).parent().fadeOut();
                        }
                    } catch(e) {
                        alert(response);
                    }
                });
            } else {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init([{'type': 'fehler', 'message': '<?php echo $this->translate('tooltip_cant_delete_exercise');?>'}]);
                obj_cad_messages.open();
            }
        };

        jQuery('.dropdown.custom-drop-down .option-add').unbind('click').click(function() {
            var selectedOption = jQuery(this).data('value');
            var selectedOptionName = jQuery(this).html();
            var caretContent = '<span class="caret"></span>';

            jQuery(this).parent().parent().parent().attr('data-value', selectedOption);
            jQuery(this).parent().parent().parent().find('.dropdown-toggle').html(selectedOptionName + caretContent).dropdown('toggle');

            return false;
        });

        jQuery('.search').unbind('click').on('click', function() {

            var exerciseType = jQuery('.exercise-type-select').attr('data-value');
            var device = jQuery('.device-select').attr('data-value');

            var currentLocation = location.href;
            var newLocation = jQuery.url(currentLocation);
            var params = newLocation.param();

            if (0 == exerciseType) {
                delete params["exercise-type"];
            } else {
                params['exercise-type'] = exerciseType;
            }

            if (0 == device) {
                delete params["device"];
            } else {
                params['device'] = device;
            }

            newLocation = newLocation.attr('base') + newLocation.attr('directory');

            if (jQuery.param(params).length) {
                newLocation =  newLocation + '?' + jQuery.param(params)
            }
            location.href = newLocation;
        });

        function initExercises() {
            function singleClick(e) {
                var id = jQuery(this).data('id');
                loadShowContent(id);
            }

            function doubleClick(e) {
                var id = jQuery(this).data('id');
                loadEditContent(id);
            }

            jQuery('.exercise').unbind('click').click(function(e) {
                var that = this;
                setTimeout(function() {
                    var dblclick = parseInt(jQuery(that).data('double'), 10);
                    if (dblclick > 0) {
                        jQuery(that).data('double', dblclick-1);
                    } else {
                        singleClick.call(that, e);
                    }
                }, 300);
            }).dblclick(function(e) {
                jQuery(this).data('double', 2);
                doubleClick.call(this, e);
            });
        }

        initExercises();

        /**
         * manipulate part of string
         */
        /**
         *
         var exerciseType = jQuery('.exercise-type-select').find('.dropdown-toggle').html();
         var device = jQuery('.device-select').find('.dropdown-toggle').html();

         var regEx = /(\(.*?\))/g;

         if (exerciseType.match('<?php echo $this->translate('label_please_select');?>')) {
                exerciseType = undefined;
            } else {
                exerciseType = exerciseType.replace(regEx, '');
            }
         if (device.match('<?php echo $this->translate('label_please_select');?>')) {
                device = undefined;
            } else {
                device = device.replace(regEx, '');
            }
         */
    });
    function showSpinner(element) {
        var spinner = jQuery('<div class="spinner"></div>');
        element.html(spinner);
    }

    function loadShowContent(id) {
        showSpinner(jQuery('#right'));

        jQuery.post('/'+controller+'/show', {id: id, ajax: true}, function(response) {
            jQuery('#right').html(response);
            scrollToAnchor('right');
        });
    }

    function loadEditContent(id) {
        showSpinner(jQuery('#right'));

        jQuery.post('/'+controller+'/edit', {id: id, ajax: true}, function(response) {
            jQuery('#right').html(response);
            scrollToAnchor('right');
            var obj_cad_cms = new jQuery('html').CAD_CMS(jQuery('.editable'), controller);
            edit_init(true);
        });
    }

    function deleteEntry(id) {
        showSpinner(jQuery('#right'));

        jQuery.post('/'+controller+'/delete', {id: id, ajax: true}, function(response) {
            jQuery('#right').html(response);
            jQuery('#'+id).fadeOut();
        });
    }

    function scrollToAnchor(aid){
        var aTag = jQuery("a[name='"+ aid +"']");
        jQuery('html,body').animate({scrollTop: aTag.offset().top},'slow');
    }
</script>