    <a name="right" />
    <div class="detail-options">
        <?php echo $this->detailOptionsContent;?>
    </div>

    <h3>
        <?php echo $this->exercise_name;?>
    </h3>

    <?php echo $this->previewPictureContent;?>

    <br class="clear-fix" style="margin-top: 15px;" />

    <?php echo $this->exerciseTypeContent;?>

    <br class="clear-fix" />

    <h3 class=""
        style="margin-top: 15px;">
        <?php echo $this->translate('label_description');?>:
    </h3>

    <br class="clear-fix" />

    <div class="col-sm-12"
         style="margin-top: 5px;">
        <?php echo $this->exercise_description;?>
    </div>

    <br class="clear-fix" />

    <h3 class=""
        style="margin-top: 15px;">
        <?php echo $this->translate('label_special_features');?>:
    </h3>

    <br class="clear-fix" />

    <div class="row">
        <div class="col-sm-12" style="margin-top: 5px;">
            <?php echo $this->exercise_special_features;?>
        </div>
    </div>

    <br class="clear-fix" />

    <h3 style="margin-top: 25px;">
        <?php echo $this->translate('label_device');?>:
    </h3>

    <br class="clear-fix" />

    <div class="form-group" style="margin-top: 10px;"><?php echo $this->device_name;?></div>

    <br class="clear-fix" />

    <?php
    if ($this->deviceOptionsContent) {
?>
        <h3 class=""><?php echo $this->translate('label_device_options');?> :</h3>

        <br class="clear-fix"/>
        <div class="device-options" style="margin-top: 25px;">
            <?php echo $this->deviceOptionsContent;?>
        </div>

        <br class="clear-fix" />
<?php
    }
?>
<?php
    if ($this->exerciseOptionsContent) {
?>
        <h3 class=""><?php echo $this->translate('label_exercise_options');?> :</h3>

        <br class="clear-fix"/>

        <div class="exercise-options" style="margin-top: 25px;">
            <?php echo $this->exerciseOptionsContent;?>
        </div>

        <br class="clear-fix" />
<?php
    }
?>

<?php
    if ($this->exerciseMuscleGroupsContent) {
?>
        <h3 style="float: left; display: inline; margin-top: 25px;">
            <?php echo $this->translate('label_muscle_groups'); ?>:
        </h3>

        <br class="clear-fix"/>

        <div class="exercise-muscle-groups"
             style="margin-top: 5px;">
            <?php echo $this->exerciseMuscleGroupsContent; ?>
        </div>

        <br class="clear-fix"/>

<?php
    }
?>

<!--    <h3 style="margin-top: 15px;">-->
<!--        --><?php //echo $this->translate('label_exercise_pictures');?><!--:-->
<!--    </h3>-->

<!--    <br class="clear-fix" />-->

<!--    <h3 style="margin-top: 15px;">-->
<!--        --><?php //echo $this->translate('label_exercise_video');?><!--:-->
<!--    </h3>-->

<!--    <div id="exercise_video"-->
<!--         style="margin-top: 5px;">-->
<!--    </div>-->

<!--    <br class="clear-fix" />-->

<script type="text/javascript" language="JavaScript">
    controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

    jQuery(document).ready(function() {
        jQuery('.detail-options .edit-button').unbind('click').click(function() {
            loadEditContent(jQuery(this).data('id'));
        });

        jQuery('.delete-button').unbind('click').click(function() {
            var that = this;
            BootstrapDialog.show({
                type: BootstrapDialog.TYPE_WARNING,
                message: '<?php echo $this->translate('question_warning_delete_exercise');?>',
                buttons: [{
                    label: 'Ok',
                    // no title as it is optional
                    cssClass: 'btn-primary',
                    action: function(dialogItself){
                        jQuery(that).deleteExercise();
                        dialogItself.close();
                    }
                }, {
                    label: 'Cancel',
                    action: function(dialogItself){
                        dialogItself.close();
                    }
                }]
            });
        });

        jQuery.fn.deleteExercise = function() {
            var exerciseId = jQuery(this).data('id');
            var that = this;

            if(jQuery.isNumeric(exerciseId)
                && 0 < exerciseId
            ) {
                var url = "/exercises/delete/";
                var obj_params = {'id': exerciseId, 'ajax': true};

                jQuery.post(url, obj_params, function(response) {
                    try {
                        json = JSON.parse(response);

                        if (200 == json.state) {
                            jQuery('#accordion #' + exerciseId).fadeOut('normal', function() {
                                jQuery(this).remove();
                            }).next().remove();
                            jQuery('#right').wrapInner('<div class="temporary">').find('.temporary').fadeOut('normal', function() {
                                jQuery(this).remove();
                            });
                        } else {
//                        var cad_obj_messages = new CAD.Message();
//                        cad_obj_messages.init(response);

//                        if(cad_obj_messages.open()) {
//                            jQuery(that).parent().fadeOut();
//                        }
                        }
                    } catch(e) {
                        alert(e.message);
                    }
                });
            } else {
//                var obj_cad_messages = new CAD.Message();
//                obj_cad_messages.init([{'type': 'fehler', 'message': '<?php //echo $this->translate('tooltip_cant_delete_exercise');?>//'}]);
//                obj_cad_messages.open();
            }
        };
    });
</script>
