<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 04.05.14
 * Time: 17:15
 */

?>

<ol class="trainingsplan droppable" style="background-color: gainsboro; border-radius: 5px; border-color: lightgray;
            margin-top: 15px; padding: 10px; font-size: 10px; color: darkslategray; position: relative;
            /*list-style-type: none;*/
            "
    id="<?php echo $this->iTrainingsplanId;?>">
    <img src="/images/content/statisch/grafiken/edit.png" style="width: 15px; position: absolute; top: 0px; right: 15px;"
         class="edit" alt="Bearbeiten" title="Hier klicken um diesen Split zu bearbeiten!" />
    <?php echo $this->sUebungen;?>
    <input type="hidden" name="trainingsplan_id[<?php echo $this->iTrainingsplanId;?>]" id="trainingsplan_id_<?php echo $this->iTrainingsplanId;?>"
           value="<?php echo $this->iTrainingsplanId;?>" />
    <li class="placeholder"></li>
</ol>
