<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 08.05.14
 * Time: 22:18
 */
?>
<?php
$vorschaubild = '/images/content/statisch/grafiken/blank.gif';
if(strlen(trim($this->uebung_vorschaubild)) > 0)
{
    $vorschaubild_pfad = '/images/content/dynamisch/uebungen/' . $this->uebung_id . '/' . $this->uebung_vorschaubild;
    if(file_exists(APPLICATION_PATH . '/../public' . $vorschaubild_pfad) &&
        is_file(APPLICATION_PATH . '/../public' . $vorschaubild_pfad) &&
        is_readable(APPLICATION_PATH . '/../public' . $vorschaubild_pfad))
    {
        $vorschaubild = $vorschaubild_pfad;
    }
}

if (FALSE === function_exists('formatFloatValue')) {
    function formatFloatValue($fValue) {
        $iValue = number_format($fValue, 0);
        if ($iValue != $fValue) {
            return $fValue;
        }
        return $iValue;
    }
}

$sUebungLink = '/trainingstagebuch/show/id' . $this->trainingsplan_uebung_id;
if (2 == $this->trainingsplan_layout_fk) {
    $sUebungLink = '/trainingsplan/show/id/' . $this->trainingsplan_uebung_trainingsplan_fk;
}
?>
<div style="position: relative;">
    <a href="<?php echo $sUebungLink;?>"
       style="text-decoration: none;">
        <h3 style="float: left; display: inline;">
            <?php echo $this->uebung_name;?>
        </h3>
        <span style="float: left; display: inline; margin: 0 10px;">
            an :
        </span>
        <h5 style="float: left; display: inline;">
            <?php echo $this->geraet_name;?>
        </h5>
        <br class="clearfix" />
        <img src="<?php echo '/butler/create-thumb/file/' . base64_encode(APPLICATION_PATH . '/../public' . $vorschaubild) . '/width/200/';?>"
             style="margin: 10px 10px 10px 0; width: 200px; float: left; display: inline;" />
        <div style="float: left; display: inline;">
            <span style="margin-top: 10px; float: left; display: inline; width: 100px;">
                Wiederholungen:
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 40px;">
                <?php echo $this->actual_uebung_wiederholungen;?>
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 100px;">
                Sätze:
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 40px;">
                <?php echo $this->actual_uebung_saetze;?>
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 100px;">
                Gewicht:
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 40px;">
                <?php echo formatFloatValue($this->actual_uebung_gewicht);?>
            </span>
            <br class="clearfix" />
            <span style="margin-top: 10px; float: left; display: inline; width: 100px;">
                Sitzposition:
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 40px;">
                <?php echo formatFloatValue($this->actual_uebung_sitzposition);?>
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 100px;">
                Rückenpolster:
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 40px;">
                <?php echo formatFloatValue($this->actual_uebung_rueckenpolster);?>
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 100px;">
                Beinpolster:
            </span>
            <span style="margin-top: 10px; float: left; display: inline; width: 40px;">
                <?php echo formatFloatValue($this->actual_uebung_beinpolster);?>
            </span>
            <br class="clearfix" />
            <span style="float: left; margin-top: 10px;">
                Bemerkung:
            </span>
            <br class="clearfix" />
            <span style="float: left; margin-top: 10px;">
                <?php echo $this->actual_uebung_bemerkung;?>
            </span>
        </div>
<!--        <img src="/images/content/statisch/grafiken/delete.png"-->
<!--             class="uebung-delete"-->
<!--             data-uebung-id="--><?php //echo $this->uebung_id;?><!--"-->
<!--             style="position: absolute; top: 0; right: 0;" />-->
        <br class="clearfix" />
    </a>
</div>
