<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 04.05.14
 * Time: 20:23
 */ 

?>

<form method="post">
    <label>
        Übung:
    </label>
    <input type="text" value="" name="trainingsplan_uebung_name" id="trainingsplan_uebung_name" />
    <input type="hidden" value="" name="trainingsplan_uebung_id" id="trainingsplan_uebung_id" />
    <label>
        Gewicht:
    </label>
    <input type="text" value="" name="trainingsplan_uebung_gewicht" id="trainingsplan_uebung_gewicht" />
    <label>

    </label>
    <input type="hidden" value="" name="trainingsplan_uebung_order" id="trainingsplan_uebung_order" />
</form>
