<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 04.05.14
 * Time: 17:15
 */

?>

<ol class="trainingsplan droppable ui-sortable" style="background-color: gainsboro; border-radius: 5px; border-color: lightgray;
            margin-top: 15px; padding: 10px; font-size: 10px; color: darkslategray; position: relative;
            /*list-style-type: none;*/
            "
    id="<?php echo $this->iTrainingsplanId;?>">
    <a href="/trainingsplan/edit/id/<?php echo $this->iTrainingsplanId;?>"
       style="width: 15px; position: absolute; top: 0px; right: 15px;">
        <img src="/images/content/statisch/grafiken/edit.png"
             alt="Bearbeiten" title="Hier klicken um diesen Split zu bearbeiten!" />
    </a>
    <?php echo $this->sUebungen;?>
    <input type="hidden" name="trainingsplan_id[<?php echo $this->iTrainingsplanId;?>]" id="trainingsplan_id_<?php echo $this->iTrainingsplanId;?>"
           value="<?php echo $this->iTrainingsplanId;?>" />
    <li class="placeholder"></li>
    <a href="/trainingstagebuch/start/id/<?php echo $this->iTrainingsplanId;?>">
        <button >
            Trainingsplan starten
        </button>
    </a>
</ol>
