<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 04.05.14
 * Time: 17:15
 */

?>

<h3>
    Übung: <?php echo $this->uebung_name;?>
</h3>
<br />
<span>
    Sätze: <?php echo $this->trainingsplan_uebung_saetze;?>
</span>
<br />
<span>
    Wiederholungen: <?php echo $this->trainingsplan_uebung_wiederholungen;?>
</span>
<br />
<span>
    Gewicht: <?php echo $this->trainingsplan_uebung_gewicht;?>
</span>
<br />
<span>
    Sitzposition: <?php echo $this->trainingsplan_uebung_sitzposition;?>
</span>
<br />
<span>
    Rückenpolster: <?php echo $this->trainingsplan_uebung_rueckenpolster;?>
</span>
<br />
<span>
    Beinpolster: <?php echo $this->trainingsplan_uebung_beinpolster;?>
</span>
