<div id="cad-cms-editor">
	 <div class="cad-cms-leiste">
	 	<button class="cad-cms-button"
	 			id="cad-cms-button-save" 
	 			title="hier klicken zum Speichern" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-bold" 
	 			title="hier klicken um Text Fett zu formatieren"
	 			data-ubb-tag="B" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-italic" 
	 			title="hier klicken um Text Italic zu formatieren"
	 			data-ubb-tag="I" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-underline" 
	 			title="hier klicken um Text mit einem Unterstrich zu versehen"
	 			data-ubb-tag="U" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb" 
	 			id="cad-cms-button-left" 
	 			title="hier klicken um einen Absatz Linksbündig auszurichten"
	 			data-ubb-tag="LEFT">
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-center" 
	 			title="hier klicken um einen Absatz zentriert auszurichten"
	 			data-ubb-tag="CENTER" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-right" 
	 			title="hier klicken um einen Absatz Rechtsbündig auszurichten"
	 			data-ubb-tag="RIGHT" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-block" 
	 			title="hier klicken um einen Absatz als Block auszurichten"
	 			data-ubb-tag="BLOCK" >
	 	</button>
	 	<button class="cad-cms-button" 
	 			id="cad-cms-button-close" 
	 			title="hier klicken zum Speichern">
	 	</button>
	 	<button class="cad-cms-button"
	 			id="cad-cms-button-help" 
	 			title="hier klicken für eine Hilfe zum Editor" >
	 	</button>
	 </div>
	 <div class="cad-cms-leiste">
	 	<button class="cad-cms-button" 
	 			id="cad-cms-button-font-size" 
	 			title="hier klicken um die Schriftgröße zu ändern">
	 	</button>
	 	<button class="cad-cms-button" 
	 			id="cad-cms-button-font-color" 
	 			title="hier klicken um eine Schriftfarbe auszuwählen" >
	 	</button>
	 	<button class="cad-cms-button"
	 			id="cad-cms-button-background-color" 
	 			title="hier klicken um eine Hintergrundfarbe auszuwählen" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-ordered-list" 
	 			title="hier klicken zum Speichern"
	 			data-ubb-tag="OL" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-unordered-list" 
	 			title="hier klicken zum Speichern"
	 			data-ubb-tag="UL" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb"
	 			id="cad-cms-button-image" 
	 			title="hier klicken zum Speichern"
	 			data-ubb-tag="IMG" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb" 
	 			id="cad-cms-button-url" 
	 			title="hier klicken um eine URL einzufügen"
	 			data-ubb-tag="URL=" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb" 
	 			id="cad-cms-button-insert-tab" 
	 			title="hier klicken zum Speichern"
	 			data-ubb-tag="TAB+" >
	 	</button>
	 	<button class="cad-cms-button cad-cms-button-ubb" 
	 			id="cad-cms-button-delete-tab" 
	 			title="hier klicken zum Speichern"
	 			data-ubb-tag="TAB-" >
	 	</button>
	 </div>
	<textarea id="cad-cms-textfeld" ></textarea>
</div>