<?php
    if(is_array($this->a_muskeln))
    {
        foreach($this->a_muskeln as $a_muskel)
        {
            $this->assign($a_muskel);
            echo $this->render('muskeln/muskel-loop.phtml');
        }
    }
?>

<script type="text/javascript">
    jQuery('document').ready(function()
    {
        jQuery('.muskel-delete').unbind('click');
        jQuery('.muskel-delete').bind('click', function()
        {
            if(confirm('Diesen Muskel wirklich löschen?\n\nAchtung:\n' +
                       'Wenn Sie diesen Muskel löschen, werden auch alle ' +
                       'mit Ihm verknüpften Muskelgruppen und Übungen gelöscht!'))
            {
                jQuery(this).loescheMuskel();
            }
        });
        
        jQuery.fn.loescheMuskel = function()
        {
            var i_muskel_id = jQuery(this).data('muskel-id');
            var that = this;
            
            if(isNumber(i_muskel_id) &&
               0 < i_muskel_id)
            {
                var url = "/muskeln/loesche-muskel/";
                var obj_params = {'id': i_muskel_id, 'ajax': true};
                
                jQuery.post(url, obj_params, function(response)
                {
                    try
                    {
                        response = JSON.parse(response);
                        var cad_obj_messages = new CAD.Message();
                        cad_obj_messages.init(response);
                        
                        if(cad_obj_messages.open())
                        {
                            jQuery(that).parent().fadeOut();
                        }
                    }
                    catch(e)
                    {
                        alert(response);
                    }
                });
            }
            else
            {
                var obj_cad_messages = new CAD.Message();
                obj_cad_messages.init([{'type': 'fehler', 'message': 'Fehler bei der Übergabe!<br /><br />Ich kann diesen Muskel leider nicht löschen!'}]);
                obj_cad_messages.open();
            }
        };
    });
</script>
