<div style="position: relative; width: 300px; margin-top: 10px;">
     <a href="/muskeln/edit/id/<?php echo $this->muskel_id;?>" 
   style="margin-top: 5px; text-decoration: none;">
    <?php echo $this->muskel_name;?>
    </a>
    <br />
    <img src="/images/content/statisch/grafiken/delete.png" 
         class="muskel-delete"
         data-muskel-id="<?php echo $this->muskel_id;?>"
         style="position: absolute; top: 0; right: 0;" />
</div>