<div class="muskel" style="margin-top: 5px; position: relative; width: 325px;">
    <input type="text" class="muskel-name"
           style="float: left;"
           value="<?php echo $this->muskel_name;?>" 
           data-muskel-name="<?php echo $this->muskel_name;?>" 
           data-muskel-id="<?php echo $this->muskel_id;?>" />
    <div style="float: left; margin-left: 10px;">
        <img src="/images/content/statisch/grafiken/beanspruchung.png" class="muskel-beanspruchung"  
                 style="background-image: url('/images/content/statisch/grafiken/beanspruchung_bg_neu.png');
                        background-repeat: no-repeat;
                        background-position: -100px 0;
                        width: 100px; height: 20px;
                        background-color: #EEEEEE;">
    </div>
        <img src="/images/content/statisch/grafiken/delete.png" 
             title="zum entfernen hier klicken!" 
             style="position: absolute; height: 20px; width: 20px;
                    right: 5px; top: 0; <?php if($this->muskel_id > 0){ echo ' display: block; ';} else
                    { echo ' display: none; ';}?>"
             class="muskel-delete" />
    <br class="clearfix" />
</div>