<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 01.05.15
 * Time: 13:16
 *
 * Version: 5.4
 */

?>

<div class="action checkbox checkbox-primary">

    <input type="checkbox"
           name="user_right_group_right_active[<?php echo $this->iInputCount;?>]"
           id="<?php echo $this->sModuleName . '_' . $this->sControllerName . '_' . $this->sActionName . '_active';?>"
        <?php
        if (true === $this->bActionChecked) {
            echo ' checked ';
        }
        if (true === $this->bActionRightInherited) {
            echo ' disabled ';
        }
        ?>
           title="<?php echo $this->sTitle;?>" />

    <label class="rotate"
        for="<?php echo $this->sModuleName . '_' . $this->sControllerName . '_' . $this->sActionName . '_active';?>"
        data-toggle="tooltip"
        title="<?php echo $this->sTitle;?>"
        ><?php echo $this->sActionName;?></label>

    <input type="hidden"
           name="user_right_group_right[<?php echo $this->iInputCount;?>]"
           value="<?php echo $this->sModuleName . ':' . $this->sControllerName . ':' . $this->sActionName;?>" />
</div>
