<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 01.05.15
 * Time: 13:09
 */
?>

<div class="controller flex-item"
     data-controller-name="<?php echo $this->sControllerName;?>" >
    <span >Controller: </span>

    <div class="checkbox checkbox-primary">

        <input class="global-check"
               name="user_right_group_right_active[<?php echo $this->iInputCount;?>]"
               id="<?php echo $this->sModuleName . '_' . $this->sControllerName . '_active';?>"
               title="<?php echo $this->sGlobalControllerTitle;?>"
               type="checkbox"
            <?php if (true === $this->bGlobalControllerChecked) {echo ' checked ';}?>
               data-orig="<?php if (true === $this->bGlobalControllerChecked) {echo ' checked ';}?>"
            <?php if (true === $this->bGlobalControllerRightInherited) {echo ' disabled ';}?> />

        <label for="<?php echo $this->sModuleName . '_' . $this->sControllerName . '_active';?>">
            <?php echo $this->sControllerName;?>
        </label>
    </div>

    <input class="global-check orig"
           name="user_right_group_right_active_orig[<?php echo $this->iInputCount;?>]"
           id="<?php echo $this->sModuleName . '_' . $this->sControllerName . '_orig';?>"
           title="<?php echo $this->sGlobalControllerTitle;?>"
           type="checkbox"
        <?php if (true === $this->bGlobalControllerChecked) {echo ' checked ';}?>
           data-orig="<?php if (true === $this->bGlobalControllerChecked) {echo ' checked ';}?>"
        <?php if (true === $this->bGlobalControllerRightInherited) {echo ' disabled ';}?> />

    <input type="hidden"
           name="user_right_group_right_id[<?php echo $this->iInputCount;?>]"
           value="<?php echo $this->iGlobalUserGruppenRechtId;?>" />

    <input type="hidden"
           name="user_right_group_right[<?php echo $this->iInputCount;?>]"
           value="<?php echo $this->sModuleName . ':' . $this->sControllerName . ':*';?>" />

    <br />

    <p>
        Actions:
    </p>

    <div class="action-container">
        <?php
            echo $this->sControllerContent;
        ?>
    </div>
</div>

