<div class="row">
    <div class="col-sm-3">
        <img src="<?php echo $this->userPreviewPictureSourceContent;?>" />
    </div>
    <div class="col-sm-9">
        <div class="form-group">
            <label class="control-label">User Vorname:</label>
<!--            <input type="text" class="form-control" name="user-first-name" id="user_first-name" value="--><?php //echo $this->user_first_name;?><!--" />-->
            <?php echo $this->user_first_name;?>
        </div>
        <div class="form-group">
            <label class="control-label">User Name:</label>
            <!--            <input type="text" class="form-control" name="user-last-name" id="user_last_name" value="--><?php //echo $this->user_last_name;?><!--" />-->
            <?php echo $this->user_last_name;?>
        </div>
        <div class="form-group">
            <label class="control-label">User Email:</label>
            <!--            <input type="text" class="form-control" name="user-last-name" id="user_last_name" value="--><?php //echo $this->user_last_name;?><!--" />-->
            <?php echo $this->user_email;?>
        </div>
    </div>
</div>