<div class="device form-group" style="position: relative;">
    <input class="device-name form-control"
           type="text"
           value="<?php echo $this->device_name;?>"
           data-device-name="<?php echo $this->device_name;?>"
           data-device-id="<?php echo $this->device_id;?>" />

    <span class="delete device-delete glyphicon glyphicon-remove-sign" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_delete_device_from_selection');?>"></span>
</div>