<div style="clear: both; margin-top: 15px; position: relative; width: 300px;">
    <a href="/device-groups/edit/id/<?php echo $this->device_group_id;?>"
       style="text-decoration: none;">
        <?php echo $this->device_group_name;?>
    </a>
    <br class="clearfix" />
<?php
    if (is_array($this->a_geraetegruppe_geraete)
        || $this->a_geraetegruppe_geraete instanceof Zend_Db_Table_Rowset
    ) {
        foreach($this->a_geraetegruppe_geraete as $a_geraetegruppe_geraet) {
            $this->assign($a_geraetegruppe_geraet->toArray());
            echo $this->render('loops/device-device-group.phtml');
        }
    }
?>
    <img src="/images/content/statisch/grafiken/delete.png"
         class="device-group-delete"
         data-device-group-id="<?php echo $this->device_group_id;?>"
         style="position: absolute; top: 0; right: 0;" />
    <br class="clearfix" />
</div>
