<div style="position: relative; width: 300px; margin-top: 10px;">
     <a href="/devices/edit/id/<?php echo $this->device_id;?>"
   style="margin-top: 5px; text-decoration: none;">
    <?php echo $this->device_name;?>
    </a>
    <br />
    <img src="/images/content/statisch/grafiken/delete.png" 
         class="device-delete"
         data-device-id="<?php echo $this->device_id;?>"
         style="position: absolute; top: 0; right: 0;" />
</div>
