<?php
    $vorschaubild = '/images/content/statisch/grafiken/blank.gif';
    if(strlen(trim($this->exercise_preview_picture)) > 0) {

        $vorschaubild_pfad = '/images/content/dynamisch/exercises/' . $this->exercise_id . '/' . $this->exercise_preview_picture . '.resized.jpg';
        if(file_exists(getcwd() . $vorschaubild_pfad) &&
           is_file(getcwd() . $vorschaubild_pfad) &&
           is_readable(getcwd() . $vorschaubild_pfad))
        {
            $vorschaubild = $vorschaubild_pfad;
        }
    }
?>
<div class="exercise" style="position: relative;">
<!--    <img src="--><?php //echo $this->previewPicture;?><!--" style="width: 200px; float: left; display: inline;" />-->
    <img src="<?php echo $vorschaubild;?>" style="width: 200px; float: left; display: inline;" />
    <div style="float: left; display: inline;">
        <a href="/exercises/edit/id/<?php echo $this->exercise_id;?>"
           style="text-decoration: none;"
           data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_exercise');?>">
            <?php echo $this->exercise_name;?>
        </a>
    </div>

    <span class="exercise-delete delete glyphicon glyphicon-remove-sign"
          data-exercise-id="<?php echo $this->exercise_id;?>"
          data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_delete_exercise');?>"></span>

    <br class="clear-fix" />
</div>
