<div class="muscle-group" data-muscle-group-id="<?php echo $this->muscle_group_id;?>" style="clear: both; margin-top: 15px; position: relative; width: 300px;">
    <span>
        <?php echo $this->muscle_group_name;?>
    </span>

    <br class="clear-fix" />

    <div class="muscles-in-muscle-group" style="margin-left: 25px;">
<?php
        echo $this->musclesInMuscleGroupContent;
?>
    </div>
    <br class="clear-fix" />
</div>
