<div class="muscle" data-muscle-id="<?php echo $this->muscle_id;?>" style="position: relative; width: 300px; margin-top: 10px;">
     <a href="/muscles/edit/id/<?php echo $this->muscle_id;?>"
        style="margin-top: 5px; text-decoration: none; float: left;"
        data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_muscle');?>">
        <?php echo $this->muscle_name;?>
    </a>

    <?php echo $this->muscleUseRatingContent;?>

    <span class="muscle-delete glyphicon glyphicon-remove-sign delete"
          data-muscle-id="<?php echo $this->muscle_id;?>"
          data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_delete_muscle_selection');?>"></span>

    <br class="clear-fix" />
</div>