<?php
//    $beanspruchung_pos_x = -100;
//
//    if($this->muskelgruppe_muskel_beanspruchung > 0)
//    {
//        $beanspruchung_pos_x = -100 + ($this->muskelgruppe_muskel_beanspruchung * 20);
//    }
?>
<div class="form-group muscle" >
    <input type="text" class="form-control muscle-name"
           value="<?php echo $this->muscle_name;?>"
           data-muscle-name="<?php echo $this->muscle_name;?>"
           data-muscle-id="<?php echo $this->muscle_id;?>"
        placeholder="<?php echo $this->translate('label_muscle_name');?>" />

    <?php echo $this->muscleUseRatingContent;?>

    <span class="muscle-delete glyphicon glyphicon-remove-sign delete"
          data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_delete_muscle_selection');?>"></span>
    <br class="clear-fix" />
</div>