<div class="muscle-group" style="margin-top: 5px; position: relative; width: 325px;">
    <input type="text" class="muscle-group-name"
           style="float: left;"
           value="<?php echo $this->muscle_group_name;?>"
           data-muscle-group-name="<?php echo $this->muscle_group_name;?>"
           data-muscle-group-id="<?php echo $this->muscle_group_id;?>"
           data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_edit_muscle_group');?>"
        />

    <span class="muscle-group-delete glyphicon glyphicon-remove-sign delete"
          data-muscle-id="<?php echo $this->muscle_id;?>"
          data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_click_to_delete_muscle_group');?>"></span>

    <br class="clear-fix" />
</div>
