<div class="muscle-group" data-muscle-group-id="<?php echo $this->muscle_group_id;?>" style="clear: both; margin-top: 15px; position: relative; width: 300px;">
    <a href="/muscle-groups/edit/id/<?php echo $this->muscle_group_id;?>"
       style="text-decoration: none;">
        <?php echo $this->muscle_group_name;?>
    </a>
    <br class="clearfix" />
    <div class="muscles-in-muscle-group">
<?php
        echo $this->musclesInMuscleGroupContent;
?>
    </div>
    <img src="/images/content/statisch/grafiken/delete.png"
         class="muscle-group-delete"
         data-muscle-group-id="<?php echo $this->muscle_group_id;?>"
         style="position: absolute; top: 0; right: 0;" />
    <br class="clearfix" />
</div>
