<!--<div class="form-group" style="float: left; display: inline">-->
<div id="<?php echo $this->optionInputId;?>" class="form-group" style="position: relative;">
<!--    <label style="clear: none; float: left; display: inline; margin-right: 15px;">-->
    <label class="control-label">
        <?php echo $this->optionLabelText;?>
    </label>
    <input class="<?php echo $this->optionClassName;?> <?php echo $this->selectClass;?> form-control option" type="text"

           data-option-id="<?php echo $this->optionId;?>"
            <?php echo $this->additionalDataInformation;?>
           data-value-orig="<?php echo $this->optionSelectText;?>"
           data-base-value="<?php echo $this->baseValue;?>"
           value="<?php echo $this->optionSelectText;?>"
           data-toggle="tooltip" data-placement="right" title="<?php echo $this->baseValue;?>"
    >

<?php
    if ($this->optionDeleteShow) {
?>
        <span class="option-delete glyphicon glyphicon-trash delete"
              data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('tooltip_delete_selection');?>"></span>
<?php
    }
?>
    <br class="clear-fix" />
</div>