<div class="form-group" style="float: left; display: inline">
<!--    <label style="clear: none; float: left; display: inline; margin-right: 15px;">-->
    <label class="control-label">
        <?php echo $this->optionLabelText;?>
    </label>
    <input class="<?php echo $this->optionClassName;?> <?php echo $this->selectClass;?> form-control option-input" type="text" id="<?php echo $this->optionInputId;?>"
           data-option-id="<?php echo $this->optionId;?>"
            <?php echo $this->additionalDataInformation;?>
           data-value-orig="<?php echo $this->optionSelectText;?>"
           data-base-value="<?php echo $this->baseValue;?>"
           value="<?php echo $this->optionSelectText;?>"
           data-toggle="tooltip" data-placement="right" title="<?php echo $this->baseValue;?>"
    >

<?php
    if ($this->optionDeleteShow) {
?>
        <img class="option-delete" style="float: left; display: inline; margin-top: 0; margin-left: -25px" src="/images/content/statisch/grafiken/delete.gif" alt="Delete Option"/>
<?php
    }
?>
    <br class="clear-fix" />
</div>