<div id="dropzone" class="dropzone col-sm-9">
    <form class="dropzone needsclick" id="upload"
          style="background-image: url('<?php echo $this->dropZoneBackgroundImage;?>'); background-position: center top;
        background-size: 100% auto; background-repeat: no-repeat;">
        <span class="dz-message needsclick">
            Drop files here or click to upload.<br />
        </span>
    </form>
</div>
<div id="dropzone_previews" class="dropzone dropzone-previews col-sm-3">
    <?php echo $this->previewPicturesThumbContent;?>
</div>
