<div class="thumb">
    <div class="thumb-delete" ></div>
    <img class="thumb-src" class=""
         src="<?php echo '/butler/create-thumb/file/' . base64_encode($this->picture[CAD_File::SYS_PFAD]) . '/height/50/width/67/prio_height/true';?>"
         data-src="<?php echo base64_encode($this->picture[CAD_FILE::HTML_PFAD]);?>"
         data-file="<?php echo base64_encode($this->picture[CAD_FILE::FILE]);?>" />
</div>