<div style="float: left; margin-left: 10px;">
    <img src="/images/content/statisch/grafiken/beanspruchung.png" class="muscle-use"
         <?php if($this->exercise_x_muscle_muscle_use > 0){ echo ' data-background-position="' . $this->usePosX . 'px ' . $this->usePosX . 'px"';}?>
         <?php if($this->exercise_x_muscle_muscle_use > 0){ echo ' data-muscle-use="' . $this->exercise_x_muscle_muscle_use . '"';}?>
         style="background-image: url('/images/content/statisch/grafiken/beanspruchung_bg_neu.png');
                background-repeat: no-repeat;
                background-position: <?php echo $this->usePosX;?>px <?php echo $this->usePosX;?>px;
                width: 100px; height: 20px;
                background-color: #EEEEEE;">
</div>
