<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 06.06.14
 * Time: 12:44
 */

?>

<!--<div id="trainingstagebuch-uebung">-->

<?php
$iFaktor = $this->iMaxBeanspruchterMuskel / 5; // 5 sind die maximale anzahl der sterne

foreach ($this->aBeanspruchteMuskeln as $sMuskelName => $iBeanspruchung) {

    $beanspruchung_pos_x = -100;
    $iReelleBeanspruchung = $iBeanspruchung;

    if($iBeanspruchung > 0)
    {
        $iReelleBeanspruchung = $iBeanspruchung / $iFaktor;
        $beanspruchung_pos_x = -100 + ($iReelleBeanspruchung * 20);
//    echo $sMuskelName . ' : ' . $iBeanspruchung . ' - ' . $iReelleBeanspruchung . ' - ' . $iFaktor . ' - ' . $this->iMaxBeanspruchterMuskel;
    ?>
    <div style="width: 200px; float: left; display: inline; position: relative; padding-right: 20px; height: 25px; font-size: 10px;">
        <span style="vertical-align: middle;">
            <?php echo $sMuskelName;?>
        </span>
        <img src="/images/content/statisch/grafiken/beanspruchung.png"
             class="muscle-use"
             style="background-image: url('/images/content/statisch/grafiken/beanspruchung_bg_neu.png');
                 background-repeat: no-repeat;
                 background-position: <?php echo $beanspruchung_pos_x;?>px <?php echo $beanspruchung_pos_x;?>px;
                 width: 100px; height: 20px;
                 background-color: #EEEEEE;
                 position: absolute;
                 right: 20px;"
             data-muscle-use="<?php echo $iBeanspruchung;?>"
             data-background_position="<?php echo $beanspruchung_pos_x;?>px <?php echo $beanspruchung_pos_x;?>px">
    </div>
<?php
    }
}

?>

    <br class="clearfix" />
    <h3>
        <?php echo $this->exercise_name;?>
    </h3>

    <table style="font-size: 10px;">
        <thead>
        </thead>
        <tfoot>

        </tfoot>
        <tbody>
            <tr>
                <td rowspan="8" style="width: 250px;">
                    <img src="<?php echo '/images/content/dynamisch/exercises/' . $this->exercise_id . '/' . $this->exercise_preview_picture;?>"
                         style="width: 200px;" />
                </td>
            </tr>
            <tr>
                <td>

                </td>
                <td alt="Wert zu Beginn des Trainingsplanes" title="Wert zu Beginn des Trainingsplanes">
                    TP
                </td>
                <td alt="Letzter eingetragener Wert aus dem Training" title="Letzter eingetragener Wert aus dem Training">
                    Ak
                </td>
                <td alt="Perspektivischer Wert für das nächste Training" title="Perspektivischer Wert für das nächste Training">
                    PS
                </td>
            </tr>
            <tr>
                <td>
                    Wiederholungen
                </td>
                <td>
                    <?php echo $this->viewGenerator()->formatFloatValue($this->trainingsplan_uebung_wiederholungen);?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->trainingstagebuch_uebung_wiederholungen;?>" />
                    <?php // echo $this->viewGenerator()->generateOptionsForUebungColumn('wiederholungen', 'trainingstagebuch_uebung_wiederholungen'); ?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->trainingstagebuch_uebung_wiederholungen_perspektivisch;?>" />
                </td>
            </tr>
            <tr>
                <td>
                    Sätze
                </td>
                <td>
                    <?php echo $this->viewGenerator()->formatFloatValue($this->trainingsplan_uebung_saetze);?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->trainingstagebuch_uebung_saetze;?>" />
                    <?php // echo $this->viewGenerator()->generateOptionsForUebungColumn('saetze', 'trainingstagebuch_uebung_saetze'); ?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->trainingstagebuch_uebung_saetze_perspektivisch;?>" />
                </td>
            </tr>
            <tr>
                <td>
                    Gewicht
                </td>
                <td>
                    <?php echo $this->viewGenerator()->formatFloatValue($this->trainingsplan_uebung_gewicht);?>
                </td>
                <td>
                    <?php echo $this->viewGenerator()->generateOptionsForExerciseColumn('gewicht', 'trainingstagebuch_uebung_gewicht'); ?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->viewGenerator()->formatFloatValue($this->trainingstagebuch_uebung_gewicht_perspektivisch);?>" />
                </td>
            </tr>
            <tr>
                <td>
                    Sitzposition
                </td>
                <td>
                    <?php echo $this->viewGenerator()->formatFloatValue($this->trainingsplan_uebung_sitzposition);?>
                </td>
                <td>
                    <?php echo $this->viewGenerator()->generateOptionsForExerciseColumn('sitzposition', 'trainingstagebuch_uebung_sitzposition'); ?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->viewGenerator()->formatFloatValue($this->trainingstagebuch_uebung_sitzposition_perspektivisch);?>" />
                </td>
            </tr>
            <tr>
                <td>
                    Beinpolster
                </td>
                <td>
                    <?php echo $this->viewGenerator()->formatFloatValue($this->trainingsplan_uebung_beinpolster);?>
                </td>
                <td>
                    <?php echo $this->viewGenerator()->generateOptionsForExerciseColumn('beinpolster', 'trainingstagebuch_uebung_beinpolster'); ?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->viewGenerator()->formatFloatValue($this->trainingstagebuch_uebung_beinpolster_perspektivisch);?>" />
                </td>
            </tr>
            <tr>
                <td>
                    Rückenpolster
                </td>
                <td>
                    <?php echo $this->viewGenerator()->formatFloatValue($this->trainingsplan_uebung_rueckenpolster);?>
                </td>
                <td>
                    <?php echo $this->viewGenerator()->generateOptionsForExerciseColumn('rueckenpolster', 'trainingstagebuch_uebung_rueckenpolster'); ?>
                </td>
                <td>
                    <input class="uebung-option" type="text" value="<?php echo $this->viewGenerator()->formatFloatValue($this->trainingstagebuch_uebung_rueckenpolster_perspektivisch);?>" />
                </td>
            </tr>
        </tbody>
    </table>
    <strong>
        Beschreibung:
    </strong>
    <div style="font-size: 10px;">
        <p>
            <?php echo $this->exercise_description;?>
        </p>
    </div>
    <strong>
        Besonderheiten:
    </strong>
    <div style="font-size: 10px;">
        <p>
            <?php echo $this->exercise_special_features;?>
        </p>
    </div>
    <br class="cleafix" />
<!--</div>-->
