<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 08.05.14
 * Time: 22:18
 */
?>

<div class="row exercise">
    <div class="col-sm-12">
        <h3>
            <?php echo $this->exercise_name;?>
<?php
        if ($this->device_name) {
?>
            an :
            <?php echo $this->device_name;?>
<?php
        }
?>
        </h3>
    </div>

    <div class="col-sm-12">
        <img src="<?php echo $this->previewSource;?>" />
    </div>

    <div class="col-sm-12">

        <?php echo $this->deviceOptionsContent;?>

        <?php echo $this->exerciseOptionsContent;?>

    </div>
    <div class="col-sm-12">
        <strong>
            <?php echo $this->translate('label_description');?>:
        </strong>
    </div>
    <div class="col-sm-12">
        <span>
            <?php echo $this->exercise_description;?>
        </span>
    </div>
</div>
