<?php

if (FALSE === function_exists('formatFloatValue')) {
    function formatFloatValue($fValue) {
        $iValue = number_format($fValue, 0);
        if ($iValue != $fValue) {
            return $fValue;
        }
        return $iValue;
    }
}

//$this->trainingPlanId = $this->trainingsplan_uebung_trainingsplan_fk;

/** @TODO den blödsinn mit dem count entfernen! **/
if (TRUE === isset($this->exercise_name)) {
    $count = $this->iCount;
    if (NULL !== $this->training_plan_x_exercise_id) {
        $count = $this->training_plan_x_exercise_id;
    }
?>

<li id="<?php echo $count;?>" class="exercise ui-state-default"
    data-exercise-id="<?php echo $this->exercise_id;?>"
    data-training-plan-exercise-id="<?php echo $this->training_plan_x_exercise_id;?>">

    <div class="form-group col-sm-12">
        <p>
            <?php echo $this->translate('label_exercise');?> : <?php echo $this->exercise_name;?>
            <span class="device" data-device-id="<?php echo $this->device_id;?>">
                <?php echo $this->translate('label_on');?>
                <?php echo $this->translate('label_device');?> : <?php echo $this->device_name;?>
            </span>
        </p>
    </div>

    <div class="col-sm-6">
<!--        <label for="device_options" style="float: left; display: inline;">-->
<!--            --><?php //echo $this->translate('label_device_options');?><!--:-->
<!--        </label>-->
        <?php echo $this->deviceOptionsSelectContent;?>
    </div>

    <div class="col-sm-6">
<!--        <label for="device_options" style="float: left; display: inline;">-->
<!--            --><?php //echo $this->translate('label_exercise_options');?><!--:-->
<!--        </label>-->
        <?php echo $this->exerciseOptionsSelectContent;?>
    </div>

    <br class="clear-fix" />

    <div class="device-options">
        <?php echo $this->deviceOptionsContent;?>

<!--        <br class="clear-fix" />-->
    </div>

    <div class="exercise-options">
        <?php echo $this->exerciseOptionsContent;?>

<!--        <br class="clear-fix" />-->
    </div>

    <br class="clear-fix" />

    <div class="form-group">
        <label for="training_plan_exercise_comment_<?php echo $this->trainingPlanId;?>_<?php echo $count;?>"
               style="width: 100px; margin-top: 5px;">
            <?php echo $this->translate('label_description');?>:
        </label>

        <textarea id="training_plan_exercise_comment_<?php echo $this->trainingPlanId;?>_<?php echo $count;?>"
               name="training_plan_exercise_comment[<?php echo $this->trainingPlanId;?>][<?php echo $count;?>]"
               class="form-control exercise-comment"
        ><?php echo $this->training_plan_x_exercise_comment;?></textarea>
    </div>
    <br class="clear-fix" style="margin-bottom: 15px;"/>
<?php
    if (TRUE === is_array($this->aBeanspruchteMuskeln)) {
        foreach ($this->aBeanspruchteMuskeln as $sMuskelName => $iBeanspruchung) {
            echo $sMuskelName . ' : ' . $iBeanspruchung . '<br />';
        }
    }
} else {
    echo "Keine Übung mit der ID " . $this->iUebungId . " gefunden!";
}
?>
</li>
<?php
