<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 04.05.14
 * Time: 17:15
 */

?>
<ol class="training-plan droppable ui-sortable" style="background-color: gainsboro; border-radius: 5px; border-color: lightgray;
            margin-top: 15px; padding: 10px; font-size: 10px; color: darkslategray; position: relative;
            /*list-style-type: none;*/
            "
    id="<?php echo $this->training_plan_id;?>">

    <?php echo $this->exercisesContent;?>

    <input type="hidden" name="training-plan-id[<?php echo $this->training_plan_id;?>]" id="training_plan_id_<?php echo $this->training_plan_id;?>"
           value="<?php echo $this->training_plan_id;?>" />
<?php
    echo $this->musclesForExerciseContent;
?>
    <br class="clearfix" />
</ol>
