<div id="<?php echo $this->name;?>" class="tab-pane fade in <?php echo $this->classActive;?>">

    <div class="row">
        <div class="col-sm-12">
            <?php echo $this->musclesForTrainingPlanContent;?>
        </div>
    </div>

    <?php echo $this->exercisesContent;?>

<?php if (true == $this->trainingPlanActive) {
?>
    <a href="<?php echo $this->startTrainingPlanLink; ?>">
        <button class="btn btn-default btn-primary">
            Start Training Plan
        </button>
    </a>
<?php
    }
?>
</div>
