<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 04.05.14
 * Time: 17:15
 */

?>

<ol class="trainingsplan droppable ui-sortable" style="background-color: gainsboro; border-radius: 5px; border-color: lightgray;
            margin-top: 15px; padding: 10px; font-size: 10px; color: darkslategray; position: relative;
            /*list-style-type: none;*/
            "
    id="<?php echo $this->training_plan_id;?>">
    <a href="/training-plans/edit/id/<?php echo $this->training_plan_id;?>"
       style="width: 15px; position: absolute; top: 0px; right: 15px;">
        <img src="/images/content/statisch/grafiken/edit.png"
             alt="Bearbeiten" title="Hier klicken um diesen Split zu bearbeiten!" />
    </a>

    <?php echo $this->exercisesContent;?>

    <input type="hidden" name="training-plan-id[<?php echo $this->training_plan_id;?>]" id="training_plan_id_<?php echo $this->training_plan_id;?>"
           value="<?php echo $this->training_plan_id;?>" />
    <li class="placeholder"></li>

<?php
    echo $this->musclesForExerciseContent;
?>
    <br class="clearfix" />

    <a href="/trainings/start/id/<?php echo $this->training_plan_id;?>">
        <button >
            Trainingsplan starten
        </button>
    </a>
</ol>
<br class="clearfix" />
