<a name="right" />
<div class="detail-options">
    <?php echo $this->detailOptionsContent;?>
</div>

<br class="clear-fix" />

<div class="col-sm-12" style="margin-top: 30px;">
    <?php echo $this->translate('label_muscle_group_name');?> : <?php echo $this->name;?>
</div>

<div class="col-sm-12">
    <h3>
        <?php echo $this->translate('label_muscles');?> :
    </h3>
</div>
<div class="col-sm-12">
    <?php echo $this->musclesContent;?>
</div>

<script type="text/javascript" language="JavaScript">
    controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

    jQuery(document).ready(function() {
        jQuery('.detail-options .edit-button').unbind('click').click(function() {
            loadEditContent(jQuery(this).data('id'));
        });
        jQuery('.detail-options .delete-button').unbind('click').click(function() {
            deleteEntry(jQuery(this).data('id'));
        });
    });
</script>
