<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 30.04.15
 * Time: 20:31
 */
?>

<form method="post" action="" onchange="submit();">
    <div class="input-group">
        <?php echo $this->userRightGroupSelectContent;?>
    </div>
</form>

<form method="post" action="">
    <div class="input-group">
        <?php echo $this->userInheritRightGroupSelectContent;?>
    </div>

    <?php echo $this->sContent;?>

    <div class="form-group">
        <input type="hidden" name="user_right_group_id" value="<?php echo $this->iUserRechteGruppeId;?>" />
        <input class="form-control ui-submit" type="submit" name="save" value="speichern" />
    </div>
</form>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('body').css('overflow', 'auto');
        jQuery('[data-toggle="tooltip"]').tooltip();
    });
</script>
