<?php
/**
 * Created by PhpStorm.
 * User: mastercad
 * Date: 30.04.15
 * Time: 20:31
 */
?>

<?php echo $this->userRightGroupSelectContent;?>

<form method="post" action="">
    <?php echo $this->sContent;?>
    <input type="hidden" name="user_right_group_id" value="<?php echo $this->iUserRechteGruppeId;?>" />
    <input type="submit" name="save" value="speichern" />
</form>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('body').css('overflow', 'auto');
    });
</script>
