<a name="right" />
<div class="form-group">
    <label class="control-label" for="device_name">
        <?php echo $this->translate('label_device_name');?>:
    </label>
    <input type="text" class="form-control" id="device_name" name="device-name"
           value="<?php echo $this->device_name;?>"
           data-cad-cms-content-orig="<?php echo base64_encode($this->device_name);?>" />
</div>

<br class="clear-fix" />

<img src="<?php echo $this->preview?>"
     class="editable preview-picture"
     alt="<?php echo $this->translate('alternate_preview_picture');?>"
     style="margin-top: 15px;"
     title="<?php echo $this->translate('tooltip_click_to_upload_picture');?>"
     id="device_preview_picture"
     data-toggle="tooltip" data-placement="right"
    />

<br class="clear-fix" />

<!--    <h3 style="margin-top: 15px; font-size: 12px;">-->
<!--        Geräte Optionen:-->
<!--    </h3>-->

<?php echo $this->deviceOptionsDropDownContent;?>

<!--    <img class="device-option-add" src="/images/content/statisch/grafiken/add_normal.png"-->
<!--         style="width: 30px; float: left; display: inline;"/>-->

<!--    <br class="clear-fix" />-->

<br class="clear-fix" />

<div class="device-options" style="margin-top: 20px;">
    <?php echo $this->deviceOptionsContent;?>
</div>

<br class="clear-fix" />

<input type="hidden" class="id" name="device-id" id="device_id" value="<?php echo $this->device_id;?>" />

<br class="clear-fix" />

<h3 style="margin-top: 15px;">
    <?php echo $this->translate('label_device_pictures');?>:
</h3>

<div class="preview-pictures"
     style="margin-top: 5px;">

</div>

<br class="clear-fix" />

<button class="save btn btn-primary btn-block">
    <?php echo $this->translate('label_save');?>
</button>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#save').unbind('click').click(function() {
            var hasErrors = false;
            var messages = [];

//        if(!jQuery.trim(jQuery('#device_name').html()).length) {
            if(!jQuery.trim(jQuery('#device_name').val()).length) {
                hasErrors = true;
                messages.push({'type': 'fehler', 'message': '<?php echo $this->translate('tooltip_device_needs_name');?>'});
            }

            var optionsList = jQuery('.device-options').find('.device-option');
            var options = [];

            for (var i = 0, len = optionsList.length; i < len; i++) {
                var option_id = jQuery(optionsList[i]).data('device-option-id');
                var option_value = jQuery(optionsList[i]).val();

                if (option_id
                    && option_value
                ) {
                    options.push({'id': option_id, 'value': Base64.encode(option_value)});
                }
            }

            if (!hasErrors) {
                jQuery().setEditedElements('device_name', Base64.encode(jQuery('#device_name').val()));
                jQuery().setEditedElements('device_id', jQuery('#device_id').val());
                jQuery().setEditedElements('device_preview_picture', jQuery('#device_preview_picture').data('file'));
                jQuery().setEditedElements('device_options', options);

                jQuery().setAjax(true);

//            CADEditSave();
            } else {
//            var obj_cad_messages = new CAD.Message();
//            obj_cad_messages.init(messages);
//            obj_cad_messages.open();
            }
        });

        jQuery('.option-add').unbind('click').bind('click', function() {

            // check if selected option already exists
            var selectedOption = jQuery(this).data('value');
            var currentOptionsList = jQuery('.device-options').find('.device-option');

            for (var i = 0, len = currentOptionsList.length; i < len; i++) {
                var option_id = jQuery(currentOptionsList[i]).data('device-option-id');

                if (option_id == selectedOption) {
//                    var obj_cad_messages = new CAD.Message();
//                    obj_cad_messages.init([
//                        {
//                            'type': 'fehler',
//                            'message': '<?php //echo $this->translate('tooltip_selected_option_already_set');?>//',
//                            'confirm_func': "jQuery('#" + jQuery(currentOptionsList[i]).attr('id') + "').effect('highlight', {}, 5000)"
//                        }
//                    ]);
//                    obj_cad_messages.open();

                    return false;
                }
            }

            // hide current option from dropdown
//            jQuery(this).parent().toggle();
            jQuery(this).parent().parent().parent().find('.dropdown-toggle').dropdown('toggle');

            jQuery.post('/devices/get-device-option-edit', {ajax: true, device_option_id: selectedOption}, function(response) {
                jQuery('.device-options').append(response);
                initOptions();
            });
            return false;
        });
        initOptions();
    });

    function deleteMuscleGroup() {
        jQuery(obj_ref).find('.muscle-group-name').data('muscle-group-name', '');
        jQuery(obj_ref).find('.muscle-group-name').data('muscle-group-id', '');
        jQuery(obj_ref).fadeOut();
    }

    function initOptions() {
        jQuery('.option-delete').unbind('click').click(function () {
            var currentOption = jQuery(this).parent().find('.option');

            if (jQuery(this).parent().hasClass('deactivated')) {
                currentOption.val(currentOption.attr('data-value-before-delete'))
                    .attr('data-value-before-delete', 0)
                    .prop('disabled', false)
                    .parent().removeClass('deactivated');
                jQuery(this).removeClass('glyphicon-refresh')
                    .addClass('glyphicon-trash');
            } else {
                currentOption.attr('data-value-before-delete', currentOption.val())
                    .val(null)
                    .prop('disabled', true)
                    .parent().addClass('deactivated');
                jQuery(this).removeClass('glyphicon-trash')
                    .addClass('glyphicon-refresh');
            }
        });
    }

</script>
