<!--<div class="col-lg-12">-->
<div class="col-lg-6" id="left">
<?php
    echo $this->devicesContent;
?>
</div>
<div class="col-lg-6" id="right">
    <?php echo $this->translate('devices_default_content');?>
</div>
<!--</div>-->

<script type="text/javascript">
    controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

    jQuery('document').ready(function() {
        jQuery('.device-delete').unbind('click').bind('click', function() {
            if(confirm('Diesen Geraet wirklich löschen?\n\nAchtung:\n' +
                       'Wenn Sie diesen Geraet löschen, werden auch alle ' +
                       'mit Ihm verknüpften Geraetgruppen und Übungen gelöscht!')
            ) {
                jQuery(this).deleteDevice();
            }
        });

        function singleClick(e) {
            var deviceId = jQuery(this).data('id');
            loadShowContent(deviceId);
        }

        function doubleClick(e) {
            var deviceId = jQuery(this).data('id');
            loadEditContent(deviceId);
        }

        function initDevices() {

            jQuery('.item').unbind('click').click(function(e) {
                var that = this;
                setTimeout(function() {
                    var dblclick = parseInt(jQuery(that).data('double'), 10);
                    if (dblclick > 0) {
                        jQuery(that).data('double', dblclick-1);
                    } else {
                        singleClick.call(that, e);
                    }
                }, 300);
            }).dblclick(function(e) {
                jQuery(this).data('double', 2);
                doubleClick.call(this, e);
            });
        }

        initDevices();
    });

    function showSpinner(element) {
        var spinner = jQuery('<div class="spinner"></div>');
        element.html(spinner);
    }

    function loadShowContent(id) {
        showSpinner(jQuery('#right'));

        jQuery.post('/'+controller+'/show', {id: id, ajax: true}, function(response) {
            jQuery('#right').html(response);
            scrollToAnchor('right');
        });
    }

    function loadEditContent(id) {
        showSpinner(jQuery('#right'));

        jQuery.post('/'+controller+'/edit', {id: id, ajax: true}, function(response) {
            jQuery('#right').html(response);
            scrollToAnchor('right');
            var obj_cad_cms = new jQuery('html').CAD_CMS(jQuery('.editable'), controller);
            edit_init(true);
        });
    }

    function deleteEntry(id) {
        showSpinner(jQuery('#right'));

        jQuery.post('/'+controller+'/delete', {id: id, ajax: true}, function(response) {
            jQuery('#right').html(response);
            jQuery('#'+id).fadeOut();
        });
    }

    function scrollToAnchor(aid){
        var aTag = jQuery("a[name='"+ aid +"']");
        jQuery('html,body').animate({scrollTop: aTag.offset().top},'slow');
    }
</script>
