<a name="right" />
<div class="detail-options">
    <?php echo $this->detailOptionsContent;?>
</div>
<h2>
    <?php echo $this->name;?>
</h2>

<br class="clear-fix" />

<?php echo $this->previewPictureContent;?>

<br class="clear-fix" />

<div class="device-options" style="margin-top: 20px;">
    <?php echo $this->deviceOptionsContent;?>
</div>

<br class="clear-fix" />

<div class="preview-pictures"
     style="margin-top: 5px;">
</div>

<br class="clear-fix" />

<script type="text/javascript" language="JavaScript">
    controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';

    jQuery(document).ready(function() {
        jQuery('.detail-options .edit-button').unbind('click').click(function() {
            loadEditContent(jQuery(this).data('id'));
        });
        jQuery('.detail-options .delete-button').unbind('click').click(function() {
            deleteEntry(jQuery(this).data('id'));
        });
    });
</script>